### ISSUE TITLE
Map appears in background when ImageBasemaps is selected in Prod mode but not in Dev mode.

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#103]
**Describe the bug**
When in Production mode the map appears in the background when displaying an image basemap instead of white background.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to Image Basemaps
2. Click on an Image Basemap

**Expected behavior**
Should be a white background that hides the map.

**Smartphone (please complete the following information):**
 - Device: IPad Pro
 - OS: 13.x
 - StraboSpot2 Version 0.5.3 

**Additional context**

**Comment by sdamaraju** [comment]
@NathanNovak Can you please help me set up a production system, to debug this issue ? locally.

**Comment by jessicagood** [comment]
@sdamaraju See how we fixed this in commit 2d053ce68aa5733e43d3c17abf06b869a720bc58. Just needed to wrap BackgroundLayer in VectorSource.
