### ISSUE TITLE
Sample Information Duplicated in StraboSpot XLS Download

### ISSUE THREAD

**Issue by da-levy** [StraboSpot/StraboSpot-Mobile#104]
**Describe the bug**

When exporting my Strabo data using the current "Download" option on Stabospot "online", the "Sample Label" for a given Spot may be assigned to multiple rows within the XLS spreadsheet. The end result is the "Sample Label" is repeated for different Spots, and it is not clear to which Spot that Sample belongs. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
**Yes**/No

This issue also occurs when I download a Open Dataset from StraboSpot "Search".

1. Go to 'Account'
2. Click on 'My Data'
3. Scroll down to 'Dataset to be downloaded'
4. Select 'Download: XLS'
5. Open 'StaboSpot_Output...xls'
6. Notice 'repetition of Sample Labels'

**Expected behavior**

I expected each "Sample Label" to be listed a single time in the Spot row to which that sample belongs.

**Screenshots**

![Screenshot (92)_LI](https://user-images.githubusercontent.com/68292240/87452390-0a8db400-c5b6-11ea-9eda-6ec9afe19970.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad Mini (5th Gen.)
 - OS: 13.5.1
 - StraboSpot V. 1.19.7

**Additional context**

**Comment by jessicagood** [comment]
@jasonash Not sure if you saw this.

**Comment by jasonash** [comment]
This is the expected behavior for the XLS download. Multiple rows per spot are exported in the event that there are multiple orientations present, such as the example above.
