### ISSUE TITLE
App quit while assigning a tag.  Keeps crashing on start. 

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#110]
**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to spot and then the tags view.
2. Click on 'Assign/Remove'
3. Assign tag.

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: IPad pro

**Additional context**
Gets to home page for a second then quits.

**Comment by jessicagood** [comment]
Should be fixed with commit 049ed4a7abc43ab83f28cecae2eee9388e79c094
