### ISSUE TITLE
Editing becomes unresponsive after a few changes.

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#112]
**Describe the bug**
When editing a feature, editing is unresponsive. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Select feature.
2. Long-press to enable editing mode. 
3. Select and drag vertexes to new position. 
4. Continue a couple times. 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPad mini
 - StraboSpot Version 0.5.3

**Additional context**
Overheating may also be a cause.  See #106

**Comment by sdamaraju** [comment]
User comments : Editing points and lines really  slow  and  generally not  very  responsive,  especially if spots  are close  together.

**Comment by sdamaraju** [comment]
@NathanNovak , I see that you mentioned this one to be reproducible, I tried to edit multiple spots multiple times in the same transaction, I don't see any responsiveness issues, can you please help me understand this issue.

**Comment by NathanNovak** [comment]
Tested the issue again and I cannot replicate it anymore.  I am closing the issue for now.
