### ISSUE TITLE
A spot in different data set which is not even turned on gets selected

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#115]
When selecting a spot, the system selects and highlights a different spot from a different data set which is not turned on yet.

I couldn't reproduce this issue consistently, might need a discussion with Doug on this.

Screenshots
![image](https://user-images.githubusercontent.com/28953643/88059914-23cccc80-cb83-11ea-9cdd-ddfc333883ce.png)

**Comment by sdamaraju** [comment]
Doug's comments : I tried to select another spot in the previous view, the system selects a line about 8 miles north ina data set that is not even turned on.

The below was the previous view, he mentioned about ; 
![image](https://user-images.githubusercontent.com/28953643/88060154-71e1d000-cb83-11ea-83f8-7c6a58987f88.png)

**Comment by sdamaraju** [comment]
@panamint55 is this bug still reproducible at all ? Can you please confirm if you could reproduce this issue during the recent testing ?

**Comment by panamint55** [comment]
Seems to be fixed.

**Comment by sdamaraju** [comment]
Closing the issue based on the confirmation received.
