### ISSUE TITLE
Show trace information for lines by default, if it is a trace.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#118]
Specifically for Line features, if they have trace information, display the trace information on the notebook panel by default, without actually clicking edit button for trace to look into the trace details.

Screenshots
![image](https://user-images.githubusercontent.com/28953643/88064589-1ca8bd00-cb89-11ea-995d-b6b9cba9f2be.png)

**Comment by sdamaraju** [comment]
User comments: For lines, could we display the trace information if it is a trace? Right now I have to go to edit to see the information.

**Comment by jessicagood** [comment]
@nicolasmroberts What are your thoughts on an updated design for this if users want to see trace data (if it's already been defined as a trace) without clicking on Edit. Do we just keep the trace data we have already open in the form, with the cancel and save buttons then too? (We wouldn't need the edit button then.) Or is there another way you think we should visualize it?

**Comment by panamint55** [comment]
It would be helpful to display Trace Quality and Trace Type and the more specific type (3 levels) if it is a trace.  So, the action would be select a line that is a trace, have it display those data, and then go ahead and display the usual below. 

Does that sound doable?

Doug

**Comment by jessicagood** [comment]
@panamint55 decided having the trace type and more specific type in the Spot header like we have already was actually good enough and quality not that important.
