### ISSUE TITLE
Zoom in, to select a spot, crashes the system

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#119]
Try to zoom in, and select a spot.

1. Zoom in and observe the zoom levels from 17.8 18.3 18.9 19.5 
2. Finally screen blacks out.

Zoom in, though the level changes, the screen display seems to be the same. Finally blacks out without showing further details.

Screenshots
![image](https://user-images.githubusercontent.com/28953643/88066789-cd17c080-cb8b-11ea-9c08-6173373f916d.png)
![image](https://user-images.githubusercontent.com/28953643/88066825-d6089200-cb8b-11ea-9319-f1c2c472feab.png)
![image](https://user-images.githubusercontent.com/28953643/88066806-d2750b00-cb8b-11ea-9076-3ba11547f68d.png)
![image](https://user-images.githubusercontent.com/28953643/88066840-dc970980-cb8b-11ea-94f0-586ea377bac5.png)
![image](https://user-images.githubusercontent.com/28953643/88066855-e3258100-cb8b-11ea-84d8-2b80c2a8e04d.png)
![image](https://user-images.githubusercontent.com/28953643/88066877-eb7dbc00-cb8b-11ea-91db-e46a0d7dc544.png)

**Comment by NathanNovak** [comment]
@panamint55 I wonder if this issue was related to the overheating and over processing from before with the Navigation dot on constantly. I can't seem to replicate the issue.

**Comment by NathanNovak** [comment]
Issue may be because of overheating and was solved in #106. Closing for now.
