### ISSUE TITLE
Edit Samples in Notebook

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#12]
Add functionality to edit/add detail to samples

**Comment by jessicagood** [comment]
This in in the Notebook page - unable to edit samples after entering.
Need to show the Samples form in the same way we do for Measurements.

**Comment by jessicagood** [comment]
Added the json for form with commit 5035b0e31ac128de4ad9a6aeb02d212fadac0f19

**Comment by sdamaraju** [comment]
Thanks for letting me know, Jessica.
Will look into it.

**Comment by sdamaraju** [comment]
Sample detail page changes are part of this commit : 5ae546f6be439c830b8db6de4338f381381c138f
