### ISSUE TITLE
Display image name and status(imagebasemap)(image details of image associated with a spot) for a spot on the notebook panel

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#120]
For a spot that has an image, display the image name and its status, on the notebook panel

1. Identify a spot that has an image and set the image to be an image-basemap
2. Click on the notebook panel for that spot and see that there are no details of the image on the notebook panel.

Expected behavior
Add relevant image details to be displayed on notebook panel showing spot details

Screenshots
![IMG_0689](https://user-images.githubusercontent.com/28953643/88068048-511e7800-cb8d-11ea-8445-d67e40940380.PNG)

**Comment by sdamaraju** [comment]
User comments: This spot has an image.  The image has a name and it is an image basemap.  We should have the name and status beside it in the blank area.

**Comment by NathanNovak** [comment]
@sdamaraju Image title pushes the edit button off screen when character length is too long in the photo description on the Overview page.

**Comment by jessicagood** [comment]
Also no need to show "Image title" when there is no image title. Maybe we don't even need the words "Image title" at all. Just display the title if it's there. And display the words "Image Basemap" below if it's an image basemap.

**Comment by sdamaraju** [comment]
![Screen Shot 2020-07-28 at 9 19 02 PM](https://user-images.githubusercontent.com/28953643/88689337-f7cbc100-d117-11ea-8b1d-46114b07c99b.png)

I removed, image title text and truncating the title to 20 characters.. 
so a 30 character title gets truncated to 20 chars and looks like the above image, let me know if it looks okay.
@jessicagood @NathanNovak

**Comment by jessicagood** [comment]
Found a note from @nicolasmroberts that he wanted a button to view an image as an image basemap below Edit in the Notebook Overview for photos. Then that button would open the image basemap.

In that case just change the words "Image Basemap" to a button saying "View as Image Basemap" if it's an image basemap. And add the button action.

@nicolasmroberts Do you have any other comments on how you want this visualized in the Overview? Do you like the trailing dots or should the title wrap? Any other style changes?

**Comment by sdamaraju** [comment]
@jessicagood 
![Screen Shot 2020-07-28 at 11 57 03 PM](https://user-images.githubusercontent.com/28953643/88706117-0c1ab880-d12e-11ea-908e-b5d3ee018162.png)

I was working on it to make it get the feel of strab01, where we removed the edit button completely and added that action on image click, imagebasemap switch will enable and disable it as image basemap(yes to be implemented, right now it just shows whether its true or false).. 

do you want me to keep it like this, or shall we keep it as it was and just add the "view as imagebasemap" functionality ?

**Comment by sdamaraju** [comment]
<img width="261" alt="Screen Shot 2020-07-30 at 3 52 02 PM" src="https://user-images.githubusercontent.com/28953643/88912263-aab52f80-d27c-11ea-9dac-eebfb6fb2d10.png">


@nicolasmroberts  I implemented as the above image, where the name shows only first 20 characters and then shows ... if its lengthier
2. View as imagebasemap, opens up the image basemap view for the image.
3. the switch component toggles the image to be a basemap or not.

Please let me know if it looks okay or if you want me to change it, please specify the changes.

**Comment by nicolasmroberts** [comment]
@sdamaraju this looks great. My only comment about images as basemaps is whether images can have a default name (can be the uuid that the photo file name has). Right now, photos default to being unnamed, so you can't make it an image baseman right away.

**Comment by sdamaraju** [comment]
@nicolasmroberts In that case, I can add a condition that shows the image basemap option only if, the title is not empty ?

**Comment by jessicagood** [comment]
@sdamaraju I think we want to leave the toggle on there even if there is not a title. But if there is not a title and the user toggles ON the image basemap toggle then the image is given a default title derived from the file name.

In SS1 I think I gave the user an alert if they tried to toggle on the image basemap without first having a title. But this way for SS2 saves a step since it creates a default title.

**Comment by sdamaraju** [comment]
closed with commit 81028c5af50277103715962ae8eb62fcadea8efb
