### ISSUE TITLE
SpotList in home menu needs more information.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#121]
Users want to include more information about spots, like tags and other data the spot possess, under the "spots list"  tab, under the home screen.

**Comment by sdamaraju** [comment]
@nicolasmroberts Can you please provide a wire frame or some way to let us know how exactly this is being visualized to be developed.

**Comment by jessicagood** [comment]
Added with commits 8c7a745f69d383238dbad7fc88de31ce7e3bcd58 and 8c7a745f69d383238dbad7fc88de31ce7e3bcd58
In the next version the Spot list will show the same info as SS1:
- an icon for the type of geometry
- 'pages' that have data (text in SS1 but icons here)
- applicable tags as subtitles

I can update if there is a different way you want to visualize @nicolasmroberts

**Comment by nicolasmroberts** [comment]
@jessicagood The spots list page is looking very good. I created transparent versions of the icons to show what data is within the spots, and uploaded them to the ui design slack channel, and again here. The titles are e.g. Tags_transparent.png, Photo_transparent.png, etc.


 [
[StraboIcons_v6.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5007229/StraboIcons_v6.zip)
](url)
