### ISSUE TITLE
Notebook panel usability changes

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#122]
1. No gestures (will be take care in #109)
2.No swipe to close notebook (similar to 1)
3. Notebook symbol only should be used to open and close the panel.
4. Position the notebook symbol at the top, replace cloud symbol with this. 
5. Notebook should open only when a new spot gets created, once closed, it is never opened, until another new spot creation.
6. Editing mode, select and edit multiple spots, notebook panel must not be opened. (Already works)
7. Selecting a spot, should not automatically open the notebook (this has to be fixed).
8. If notebook panel is opened, it remains opened till it is closed manually.

Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Comment by NathanNovak** [comment]
Fling gestures were removed with commit 4f88a1d38a2066a947a23e04de4bc8a58dc7c848 from #109

**Comment by jessicagood** [comment]
With commit 0c3fa2ec9a87e0b6531cb534dc07d7fc983b0797 the notebook panel is not opened automatically unless a new Spot has been created. From issue #108

**Comment by NathanNovak** [comment]
New Icons and repositioning of notebook button done with commit fc6f1d782be6c840c5940f5d43e636ebfb7f6a50
