### ISSUE TITLE
Editing mode when measurements or notes or tags are clicked

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#123]
Clicking on an item like measurements  or notes  or  tags  in the  notebook should  move you directly  to an editing mode.

**Comment by sdamaraju** [comment]
@jessicagood @nicolasmroberts can this be closed as not required / not necessary ? 

based on this comment in #145 by Nick.
Yes, I agree @jessicagood @sdamaraju . I think the symbols are too much next to each header. I personally don’t thing that tapping on the header should doing anything, because people will accidentally tap while looking at their data.

**Comment by jessicagood** [comment]
I was wondering if this is actually a different issue where if when you click on the notes icon and the notes page opens if you want to edit the field you do not have to click again on the text input. 

So for notes, if there is not already a value for notes, have the cursor appear already in the text box and the keyboard opens. Though this notes page may be going away.

Same for Samples but I don't see how it's applicable to Measurements.

**Comment by sdamaraju** [comment]
Technically, this is applicable only for notes. (as measurements and samples use form.js), closing with commit c57df043a6ff4b04c5e5bf9519aeae5eabcd1243
