### ISSUE TITLE
Intermittent issues with Offline maps.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#125]
User inputs : 
Offline map tiles are flakey.  Sometimes they say they are  downloaded but do not appear.  I put  a powerpoint up about this on dropbox.  This  is  also on some  of  the videos  in  dropbox.

Please see : https://www.dropbox.com/home/Debugging%20Strabo?preview=offline+download+7-15-2020.pptx

**Comment by NathanNovak** [comment]
Same referenced issues #200 #81. 
Fixed with commits 6568adb2fec230fd1bd3aa2ced5e84da7343005b, 3398c1e948793f8521b5a729f77fb313280e3858, 56d35134e893f4b96e4af1d737a586e11f72d452, a1170e8601707e1dbbcc24a807639281119e4cd2, 6a3947e564b0e46ddc2182a516576c1b0c114493,
