### ISSUE TITLE
Issue with spot details display on Notebook header

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#133]
Notebook header shows spot details on multiple lines and misses some data for imagebasemap spots.

Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Set a spot on imagebasemap
2. Check the notebook header, misses some details

Screenshots..
![Screen Shot 2020-07-27 at 8 58 56 PM](https://user-images.githubusercontent.com/28953643/88561105-9a1e7280-d04c-11ea-93d0-9a9ab6d315ea.png)

**Comment by sdamaraju** [comment]
@nicolasmroberts : Please suggest if you want us to increase the header size to fit in all the content or want to use abbrevations like N, E, W, S for North east west and south ? and X, Y for Xpx and Ypx.

**Comment by nicolasmroberts** [comment]
@sdamaraju In this order, here are things you can do to reduce space as needed: 1) use cardinal direction abbreviations; 2) make font size slightly smaller; 3) round the displayed coordinates to one less decimal place than currently exists. NOTE: of course, store the full coordinate data (unrounded).

**Comment by sdamaraju** [comment]
@nicolasmroberts Hello nick, just with the cardinal direction abbreviations the header looks like this and the space looks good. 
It doesn't need any further resizing or one decimal cut.

Please let me know if this looks okay ?
![Screen Shot 2020-08-04 at 8 05 14 PM](https://user-images.githubusercontent.com/28953643/89306782-f5281900-d68d-11ea-84e8-f5f5c39a83da.png)

**Comment by nicolasmroberts** [comment]
Yes, that looks good!

**Comment by sdamaraju** [comment]
closed with commit 81028c5af50277103715962ae8eb62fcadea8efb
