### ISSUE TITLE
Drop down menus selections have to be touched twice

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#137]
**Describe the bug**
When making a selection in a dropdown menu (i.e. in measurements detail) the item has to be touched twice before it is selected.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to Measurements Detail
2. Click on dropdown menu field
3. select item

**Expected behavior**
Only one touch to expand the dropdown and one touch fr selection.

**Comment by jessicagood** [comment]
Fixed after several package updates (though `react-native-multiple-select` not updated). Maybe with `react-native` update 409d5b5bf5558411f3843354ab569d159e20cad2 or `react-native-elements` update 4e17ed7f595606e67d044325c23417ad95728339.
