### ISSUE TITLE
Notebook Panel Display changes

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#145]
There are both white and gray bands.  Data is in white.  Measurements and tags have gray lines because they have data.  Photos and notes do not.  Seems inconsistent and it makes me think photos and tags are grouped.  No divider between the spot and location and measurements. 

Gray is not visible in the sun.  

How about all white and lines.

Also, clicking headers does nothing.  Also, samples is not in the list but not in symbols at the bottom.  This is not consistent.  

How about:
All white
Heavy line under point
Lines between all sections
Add samples to between tags and notes.
Put the symbols beside the names as well as at the bottom.  Like camera next to photos.  Then click to take the action.

**Comment by sdamaraju** [comment]
![image](https://user-images.githubusercontent.com/28953643/90384208-d4ed5680-e09e-11ea-95fa-fcf1e3fbd443.png)

**Comment by sdamaraju** [comment]
@nicolasmroberts can you please have a look at the below notebook panel and see if it matches with the expectations.
Else please suggest changes accordingly.

Includes changes for issue #145 , #123 and #146 

<img width="297" alt="Screen Shot 2020-08-20 at 12 15 37 AM" src="https://user-images.githubusercontent.com/28953643/90677111-898f9f80-e27a-11ea-8c5a-9bcff9eb7094.png">
<img width="305" alt="Screen Shot 2020-08-20 at 12 15 48 AM" src="https://user-images.githubusercontent.com/28953643/90677121-8b596300-e27a-11ea-93e9-0bce61472821.png">

Thanks,
Sai

**Comment by jessicagood** [comment]
In my opinion the section header dividers look too cluttered with the icons in them. @nicolasmroberts I've told @sdamaraju to hold off on this part unless you really want the icons there. The sections dividers could still be clickable and take you to the appropriate notebook page just like the tabs on the bottom.

**Comment by nicolasmroberts** [comment]
Yes, I agree @jessicagood @sdamaraju . I think the symbols are too much next to each header. I personally don’t thing that tapping on the header should doing anything, because people will accidentally tap while looking at their data.

**Comment by nicolasmroberts** [comment]
@sdamaraju samples are still not listed in the notebook overview page.

**Comment by sdamaraju** [comment]
@nicolasmroberts @jessicagood 
Samples are listed, could you please check the second image.
So shall I remove the symbols and leave the notebook panel as is, and the action buttons are always in the footer ?

**Comment by jessicagood** [comment]
@sdamaraju Is the Samples fix only a local change? The Samples are not added to the overview in the master code. They should be added here. https://github.com/StraboSpot/StraboSpot-Mobile/blob/d07c91d4494689b6e46bec9e3e0875f829f0c271/src/modules/notebook-panel/Overview.js#L31

And yes, remove the icons and actions from the section dividers? Thanks.

**Comment by sdamaraju** [comment]
Closing with commit c161e17a11a7cf4d64073ce6373ec766507f3b62
