### ISSUE TITLE
Picture description does not save

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#15]
When picture is open for editing, description does not get saved. When you add a name and description, close the image, and open it back up, the description has been replaced by the image name. HOWEVER, if you say “show more fields”, the description is still there.

**Comment by sdamaraju** [comment]
@nicolasmroberts : This has been fixed as part of one of the previous commits, please let us know if we can close this issue.

**Comment by sdamaraju** [comment]
@jessicagood can you please see this and let me know if I'm missing anything or if this can be closed immediately.

**Comment by sdamaraju** [comment]
@nicolasmroberts can you confirm closure on this too.

**Comment by nicolasmroberts** [comment]
Seems to work now
