### ISSUE TITLE
Feature Colors on the Map

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#154]
@nicolasmroberts I know that there has been talk about being able to individually color points, line and polygons on the map. With the latest release you can apply a color to tags by selecting the box in the upper right of the tag info view. For polygons that have a geologic unit tag with color that color will be used when displaying the polygon on the map. How do you want the UI for this changed, if at all, and how do you want the UI to look when assigning colors to Spots?

**Comment by jessicagood** [comment]
Per team meeting today: 
- [ ] Use color for point Spots if Spot has a colored geologic unit tag, as we currently do for polygons.
- [ ] Use colored conceptual tags like colored geologic unit tags.
- [ ] Have toggle in the Map Symbols dialog to switch between coloring features by geologic unit tags or conceptual tags.

**Comment by jessicagood** [comment]
Added with commit 4a23b664ea529577004b80158672057029793cf8

**Comment by jessicagood** [comment]
@nicolasmroberts What wording do you want to use to toggle between the geologic unit tags and concept tags? I called it 'Tag Color Prioritization' but I don't really like that. Any other changes to the look of the toggling between the 2 tags? Nathan is uploading the latest version now.

**Comment by nicolasmroberts** [comment]
@jessicagood How about "Show Tag Color" with its own on-off toggle. If on, then color is displayed and the user must pick between the two choices

**Comment by jessicagood** [comment]
Ok changed this with commit d66886b2b32b21ea549a1e879a443b1a9874cd8d
