### ISSUE TITLE
Change mapStateToProps and mapDispatchToProps

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#157]
Change `mapStateToProps` and `mapDispatchToProps` to `useSelector` and `useDispatch` instead.

**Comment by NathanNovak** [comment]
Done with commit ae7e47c937e5b81b4d96eb49617b6ae9f54986b6, a860b0ae38b4fb73cc451a4a8e58f47690a21cf8
