### ISSUE TITLE
Drawing Spots slow

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#163]
Figure out why drawing Spots is slower than when there are more Spots.

**Comment by sdamaraju** [comment]
@panamint55 is this issue still being experienced ? I downloaded the fc-24 with blue-ridge and temple canyon, and tried to draw different spots, they were all drawn instantaneously without any lag. Can you please confirm if there is any specific case where the spots drawing is really slow. 

I zoomed to the spots extent and started drawing my spots where all other spots are located, there is no much difference in performance observed from my end (comparing the spots being drawn when there are lot of spots to spots being drawn where there are no spots at all.)

**Comment by panamint55** [comment]
Not sure.  I will look at this tomorrow.

**Comment by sdamaraju** [comment]
"I think things  are  ok on  speed, so you   can  drop  that   issue".
Closing this issue based on above message from @panamint55 on slack.
