### ISSUE TITLE
Replace rn-fetch-blob Package

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#172]
`rn-fetch-blob` is no longer being supported so find a replacement package and then fix and test usages.

- We're already using `react-native-fs` so may be use this?
-` rn-fetch-blob` issues suggest using `unimodules` and `expo-file-system`

Which above option is better for what we need? Should ultimately just be using a single package for file system management.

**Comment by NathanNovak** [comment]
done with commit 97bd2072fe78de663deec5e45413f9224121eada, 69183d885e77a448ae5861c2c440c7cdea900cd4, and 6de33704907880f89e425974926383f1aecaf9b9
