### ISSUE TITLE
Add ability to delete image

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#176]
Lots of conditions to check before deleting, like we don't want to delete the image if it's being used as an image baseamap. Check code in SS1 for this.

**Comment by sdamaraju** [comment]
@nicolasmroberts Please provide us with an icon that implies the delete action.

**Comment by nicolasmroberts** [comment]
@sdamaraju delete action for what? As in, delete a measurement, or delete a photo?

**Comment by sdamaraju** [comment]
@nicolasmroberts  Sorry, my bad, an icon to delete a photo

**Comment by nicolasmroberts** [comment]
@sdamaraju I'll try to get to that this afternoon.

**Comment by nicolasmroberts** [comment]
[StraboIcons_v9.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5556812/StraboIcons_v9.zip)
@sdamaraju @jessicagood new icon set with new "Delete" and "Delete_pressed" icons

**Comment by jessicagood** [comment]
@nicolasmroberts The delete icon should be in a button to match `NoteButton.png` and `SketchButton.png` See below for how it looks currently. Thanks.

![image](https://user-images.githubusercontent.com/1493985/100004097-3b5fd000-2d84-11eb-9fdd-693f011f6e73.png)

**Comment by sdamaraju** [comment]
Closing this issue with commit d28f44017ab10dba8a30f838132f5b59fc67c3b9

**Comment by nicolasmroberts** [comment]
[StraboIcon_v10.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5623557/StraboIcon_v10.zip)
Here is v10 of icons, with DeleteButton, DeleteButton_pressed added.

**Comment by jessicagood** [comment]
@nicolasmroberts Did you want the icon blue like it is in this new version?
![Screenshot_20201201-100031_StraboSpot2](https://user-images.githubusercontent.com/1493985/100772633-18a16d00-33bd-11eb-8057-731dfc6cbaf5.jpg)

**Comment by nicolasmroberts** [comment]
@jessicagood no, that is an error. Here is the replacement.

[StraboIcons_v10.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5624344/StraboIcons_v10.zip)

**Comment by jessicagood** [comment]
Ok I updated those
