### ISSUE TITLE
Deleting foliation-lineation pair after crashing

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#179]
**Describe the bug**
On occasion, a foliation-lineation pair gets added but cannot be edited. When looking at the details, both the foliation and lineation are highlighted, and the lineation is uneditable. 

However, because you cannot delete the foliation measurement without deleting the lineation measurement first, this measurement cannot be deleted. 

I suggest that foliation-lineation measurements can be deleted all at once, with a modal that pops up saying "are you sure you want to delete both the planar and linear measurement?" 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35352527/95483275-a4b28d80-0954-11eb-9599-dcf5f7604b51.png">

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - StraboSpot Version [e.g. 1.84]

**Additional context**

**Comment by jessicagood** [comment]
The two measurements were given the same Id on creation.

Fixed with commit 6b3b7ec.
https://github.com/StraboSpot/StraboSpot-Mobile/blob/ad48bf654794a53b30289f3ae6c2feef0aaae72b/src/modules/compass/Compass.js#L234
