### ISSUE TITLE
line format: Plunge → Trend

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#18]
The linear measurements should have the format Plunge → Trend (see unicode info below for arrow) in the notebook measurement view. That’s the 2 digit number first, the 3 digit number first (055 rather than 55) second. NOTE: this is kind of the opposite from how we record strikes and dips. 
→
RIGHTWARDS ARROW
Unicode: U+2192, UTF-8: E2 86 92

**Comment by jessicagood** [comment]
Fixed with commit 09d64fe1c5acf40510b2fff249cedf5ef902e29d
