### ISSUE TITLE
Compute plunge and trend from rake

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#180]
We need to add the feature back in that exists in strabo1 to compute the plunge and trend from a rake given to an associated linear feature.

**Comment by jessicagood** [comment]
Added with commit bb0b65b2992bf4cb48636a9b02cd9d323540b440

**Comment by jessicagood** [comment]
@nicolasmroberts Can you check this out in the next release and close if it looks good?

**Comment by nicolasmroberts** [comment]
Woo! This works great. I like that it automatically calculates the Trend and Plunge from the rake as you type it.
