### ISSUE TITLE
Images fail to upload when backing up to server

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#181]
When clicking "Upload project to StraboSpot", the modal hangs on the first image. I've tried this with several different projects as well as both photos taken from within strabospot as well as uploaded from camera roll. 

On strabospot.org, all the data gets successfully uploaded, but the pictures are all "IMAGE NOT FOUND" pngs

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35352527/95484008-8c8f3e00-0955-11eb-800f-a1e684af3ff6.png">

**Comment by nicolasmroberts** [comment]
Also, when you click away from the modal, it just disappears and seems to stop the process. This should not happen, right?

**Comment by jessicagood** [comment]
Uploading fixed with react native update, commit 652889c8adff47ded99117b4c917cf10bc8ca49f
