### ISSUE TITLE
Notes on notebook overview should be fully displayed

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#183]
Notes are currently cutoff after two lines when viewed in the notebook overview. They should be fully viewable, with perhaps a "show less" blue text at the bottom to partially collapse the note. If you are looking at the notebook overview page, you really want to be able to read the whole note right there.

**Comment by sdamaraju** [comment]
Hello @nicolasmroberts please see the attached screen shots and let us know if we have to implement this.
If we show a lot if text it looks a bit odd, or may be if we move the notes from being the first one in the order of display items in the overview to the last one, then it can look better (I feel).
If we have a lot of text, we cannot see other paradigms of the spot unless we scroll.
Please suggest.
<img width="259" alt="Screen Shot 2020-11-16 at 12 20 30 PM" src="https://user-images.githubusercontent.com/28953643/99221375-799a4400-2806-11eb-88df-35e63a261264.png">
<img width="256" alt="Screen Shot 2020-11-16 at 12 20 43 PM" src="https://user-images.githubusercontent.com/28953643/99221378-7bfc9e00-2806-11eb-90ca-b9264a7db806.png">

**Comment by nicolasmroberts** [comment]
@sdamaraju , I see your point. How about limit the viewable text to a max of something like 15 lines. Right now it's limited to just 2 or 3. 15 would mean that most of the time you could seen the whole note, but if it is really long you need to tap to see more.

**Comment by sdamaraju** [comment]
@nicolasmroberts  sure thing. Thanks for your inputs.

**Comment by sdamaraju** [comment]
closed with commit c57df043a6ff4b04c5e5bf9519aeae5eabcd1243
