### ISSUE TITLE
Autosave associated foliations/lineations

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#184]
When switching between the foliation and associated lineation (or lineation and associated foliation), the modal that pops up asking the user if they want to save is unnecessary. When switching between them the data should autosave. 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35352527/95484781-85b4fb00-0956-11eb-85da-cafa74b1ec05.png">

**Comment by jessicagood** [comment]
@nicolasmroberts Autosaving here would be contrary to how we use the notebook panel. If we autosave and then the user presses cancel the data would still remain. Are you sure you want this change?
