### ISSUE TITLE
If you navigate away before saving edits, pop up a modal

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#185]
If you are in the middle of a measurement but you accidentally hit "sample" or navigate away, the measurement does not save. A modal should pop up to allow the user to save, discard, or cancel the navigation.

**Comment by jessicagood** [comment]
Unfinished See work in branch with commit 082390e5bfacc067f3b79bc22153cac063ec516c

**Comment by jessicagood** [comment]
Working in [RockSubpage ](https://github.com/StraboSpot/StraboSpot-Mobile/blob/master/src/modules/petrology/RockSubpage.js) already

**Comment by jessicagood** [comment]
Added this for Measurements in commit 1cc1c81b8b525dd332c228423e2933065e298a7f

Already also in Fabrics, Minerals/Reactions, and 3D Structures.

**Comment by jessicagood** [comment]
Added to Samples with commit e0145e9cc8c78576752c6a101a36713f9f480e01

**Comment by jessicagood** [comment]
@nicolasmroberts I think I have this working on all of the pages that need it (as of the next release @NathanNovak puts out). If you see another page or don't like how this works let me know. Otherwise you can close this issue.
