### ISSUE TITLE
useSelector in VertexDrag.js has issues with the dragging to endVertexCoords.

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#189]
**Describe the bug**
When converted mapStateToProps to useSelector there is an issue when dragging a vertex while in editing mode. The end coords of the vertex would get set multiple times causing the point to "chase" off the screen. See commit : ac3de106f7315b6b96222e35220bbf175b2b2864

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  IPad
 - OS: iOS14
 - StraboSpot Version 0.13.0

**Additional context**
Left as mapStateToProps and connect to get functioning.

**Comment by sdamaraju** [comment]
Closing this issue with commit 8fb945c680d115a29755da1584fb767eca66eb01
