### ISSUE TITLE
Associated line doesn't work

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#19]
When you add an associated line, nothing happens, it just adds a line with a measurement of ?/?. 

Tapping "add associated line" should bring up the measurement tool with the “Linear Feature” toggle on

**Comment by jessicagood** [comment]
Fixed with commit 34f31973ff178d9dc938c6f0b612a341af285944

@nicolasmroberts Can you confirm this is as you wanted?

**Comment by nicolasmroberts** [comment]
yes, works well.
