### ISSUE TITLE
iOS Autosleep Upload Error

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#193]
Discovered by @panamint55 when an iOS device goes into autosleep if an upload is running the upload stops and prints out a failed message

**Comment by sdamaraju** [comment]
@panamint55 @jessicagood How long does it take for the ios device to go to autosleep ? I was working on the fc24-19 data upload and the ios device never went into sleep mode at all.

**Comment by NathanNovak** [comment]
fixed with commit 48353c2fcb411b46e9384d656348d5b3b19fa49b
