### ISSUE TITLE
Linear + planar appearance notebook view

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#20]
The Linear + planar measurements need to have both the strike/dip and the plunge → trend

**Comment by jessicagood** [comment]
@nicolasmroberts

**Comment by nicolasmroberts** [comment]
@jessicagood In that case, print "multiple lines" instead of printing the measurement.

**Comment by jessicagood** [comment]
Fixed with commit 1685207a8a7c9ae23c73d0e9dd84a9428019867c

@nicolasmroberts If it looks good in the next release can you close this issue?
