### ISSUE TITLE
Icon Needed: Open Spot

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#203]
@nicolasmroberts We need a button icon for the action of opening a Spot in the Notebook from the Images Slideshow.

**Comment by nicolasmroberts** [comment]
ok I'm on it

**Comment by nicolasmroberts** [comment]
[StraboIcons_v11.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5655642/StraboIcons_v11.zip)

Updated icons with "NotebookNav" family -- "NotebookNavButton", "NotebookNavButton_pressed", "NotebookNav", and "NotebookNav_pressed"

**Comment by nicolasmroberts** [comment]
@jessicagood there's the new icons you asked for

**Comment by jessicagood** [comment]
Fixed with commit ed8fef960adc186768cd8222bce2200e37d147ed
