### ISSUE TITLE
Data Page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#209]
Get this page working. Accessed in the notebook from the More menu. There is already a placeholder page. See Strabo Spot 1 for functionality. Does not use any form assets.

**Comment by NathanNovak** [comment]
done with commits 43b761e137e2b3b31b744d317b1cbb177e6ea0a4, 34388803a1e09b549e7de895b59e3253b33aa043, and 9de8c4b965a87ed6a7a604a48cdbdc135be6a166
