### ISSUE TITLE
Manual input of measurements

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#21]
We need a way to input a manual measurement (measured with another compass). Maybe a text button that drops down the fields. (mockup coming next week)

**Comment by nicolasmroberts** [comment]
I'll mock this up

**Comment by jessicagood** [comment]
@nicolasmroberts

**Comment by nicolasmroberts** [comment]
@jessicagood I think this one warrants some discussion. Maybe we can have a quick zoom about it this week. There are several options.

**Comment by nicolasmroberts** [comment]
Here is what we decided from our zoom call:

There is going to be blue text button in the compass measurement window to “enter manually in notebook”. That button presents the measurement detail view for a blank measurement corresponding to the toggle switches in the compass measurement window (planar measurement and/or linear measurement)

**Comment by jessicagood** [comment]
Added with commit 931ae5b01d8de2f2e556fe75cfc0ec9f81b439b4.

@nicolasmroberts Can you check the implementation in the next release and close if it looks good?

**Comment by nicolasmroberts** [comment]
@jessicagood This is working well, but it has some weird behaviors that need to be fixed. First, after tapping the red text in the modal, the notebook opens with a blank measurement. That works perfectly. However, if you keep tapping the red text, it will keep creating new blank measurement pages without saving any changes to the manual measurements that came before. That should not happen. **The desired behavior is that you need to hit "save" or "cancel" in the notebook before being able to create a new manual measurement in the measurement window.** 

Second, hitting "cancel" on the blank measurement does not actually cancel creating that measurement (See video attached). So it could get pretty frustrating if you've accidentally pushed the manual measurement and then hit cancel, you'll end up with a bunch of blank measurements. **The desired behavior is for the "cancel" button in the notebook view is to actually delete the measurement if the measurement is blank.** Because in that instance, the user is communicating that they truly did not mean to create the measurement. 

Let me know if that makes sense.

**Comment by jessicagood** [comment]
@nicolasmroberts Can you see if that works better in the next release with commit 6b3b7ec066f98922f09d34e81bc769a901e86f53

**Comment by nicolasmroberts** [comment]
Everything looks good except: 

"The desired behavior is for the "cancel" button in the notebook view is to actually delete the measurement if the measurement is blank."

has not been implemented. If the user taps to create a blank measurement, then hits cancel, the blank measurement gets saved. It should disappear.

**Comment by jessicagood** [comment]
@nicolasmroberts What exactly are the steps your are taking? @NathanNovak nor I can recreate the problem. We hit the text in the compass to create a manual measurement and then press Cancel in the detail pane and the measurement does not save.
