### ISSUE TITLE
Line disappears when in editing mode

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#216]
**Describe the bug**
When selecting a line to edit the line disappears but the vertices remain.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Expected behavior**
The line should remain while editing vertices
 
**Screenshots**
![image](https://user-images.githubusercontent.com/35514146/102636793-54a13580-4112-11eb-810e-1236138086b3.png)

**Smartphone (please complete the following information):**
 - StraboSpot Version [e.g. 1.84]

**Comment by sdamaraju** [comment]
Hi Nathan, 

I just pulled latest and here is the screen shot I have, I'm unable to reproduce this issue.

<img width="361" alt="Screen Shot 2020-12-22 at 10 57 06 PM" src="https://user-images.githubusercontent.com/28953643/102916282-4acc5900-44a9-11eb-81fb-f5ab3b257047.png">

**Comment by jessicagood** [comment]
Is there a difference between freehand vs segmented lines?

**Comment by NathanNovak** [comment]
Seems there are a lot more vertices on the freehand lines then what is displayed in the pic above

**Comment by sdamaraju** [comment]
@NathanNovak Identified the rootcause of the issue and fixed, will get it reviewed tomorrow.

**Comment by sdamaraju** [comment]
Map symbology is missing for the new line being created. That is causing the issue, setting the symbology on spot creation.
