### ISSUE TITLE
Ig/Met data values do not reset when pressing cancel

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#218]
**Describe the bug**
When copying values from one spot to another in the Ig/Met page and pressing cancel the values do not change.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to '.Ig/Met' page from notebook tools
2. Click on 'Copy Petrology Ig.Met Data'
3. Press' Cancel

**Expected behavior**
Form should reset

**Screenshots**
![image](https://user-images.githubusercontent.com/35514146/102666258-b4640480-4143-11eb-8e30-bcb0314757f3.png)

**Comment by jessicagood** [comment]
Fixed with commit 2d78da635efe234ae31b3c699f7f8bae5b2c413f
