### ISSUE TITLE
Need to be able to delete measurements

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#22]
No way to delete measurements — should be an option when you select one or more (with a modal that confirms deletion!)

**Comment by jessicagood** [comment]
With commit 7cfcd0a8ac41c94cba21c7e3b603253faf52a56d single measurements can be deleted from a button at the bottom of the measurement detail page. Still need to add ability to delete from the measurements page when one or more measurements are selected.

**Comment by NathanNovak** [comment]
Didn't see that there was still work need t be done to close this.

**Comment by jessicagood** [comment]
Yeah, still need to add ability to delete from the measurements page when one or more measurements are selected.

**Comment by jessicagood** [comment]
Added with commit 00788ea5243535b51aa1af0e445ca62b2521d461

If this is what you had in mind @nicolasmroberts you can close this issue.

**Comment by nicolasmroberts** [comment]
Looks good!
