### ISSUE TITLE
Images do not load from device backup

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#221]
**Describe the bug**
I am uploading a project from backup, and the images do not appear to transfer over from the backup into the project. I just get a bunch of grey boxes with spinning indicators.

So I backed up project to device, did a clean install of Strabo (deleted the app), and then copied the backup from my computer into the strabospot2 files folder on the iPad, and then loaded project from device in Strabo2. 

Nathan said it was a Redox issue that he had encountered with offline maps.

**Comment by NathanNovak** [comment]
fixed with commits 00209f8704cec72505cab5a0c48caa2a9a078959 and b0a37a6b239c0c3450fc8eb13f3c32406b45c217
