### ISSUE TITLE
Testing uploading movies

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#222]
just a test.  Tell me if this works.

Also, files must be less than 10MB, so I will have to look at compressing or sending a link.

So I turned this movie into 480.  See if that is sufficient for you.

https://user-images.githubusercontent.com/9283127/105214289-6dd44200-5b15-11eb-92f5-4e53cfbd21d4.mov

**Comment by NathanNovak** [comment]
Yes it works
