### ISSUE TITLE
Need Database Details mockup

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#223]
@nicolasmroberts Can you mock up Database Details along with what you want to have done inside?

**Comment by nicolasmroberts** [comment]
![Screen Shot 2021-04-09 at 9 25 30 AM](https://user-images.githubusercontent.com/35352527/114194873-89c9d180-9915-11eb-85ca-d0e5dc4f4430.png)
![Screen Shot 2021-04-09 at 9 25 50 AM](https://user-images.githubusercontent.com/35352527/114194908-951cfd00-9915-11eb-9f8d-70b996ad26d7.png)

**Comment by nicolasmroberts** [comment]
@NathanNovak I think you can close this issue
