### ISSUE TITLE
Downloading images

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#226]
It worked fine downloading the legacy project.  I then went to fc24-19 field camp 2019.  It got stuck at 73 or 74 images on North Twin.  Others worked great.

**Comment by NathanNovak** [comment]
Ok I will log into fc24-19 and take a look later today.

**Comment by NathanNovak** [comment]
@panamint55 I cannot get it to slow down or crash when in production mode.

**Comment by NathanNovak** [comment]
I am going to close this one cause I can not replicate the issue.
