### ISSUE TITLE
zoom level not showing when  the left menu is open

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#227]
When you have the settings and preferences open the zoom level does not show,  it is hidden.

3dot,star,layers, and geolocate move  right,  but not the zoom.

**Comment by NathanNovak** [comment]
Yeah the animation would not work with the zoom unless I added every zoom interval to redux, but I fear that would be a performance hit with all the calls.  I can place the zoom somewhere else on the map that a slide-out won't cover it up if you want.

**Comment by NathanNovak** [comment]
@nicolasmroberts I am going to move the zoom back up to the top-center and keep it displayed all the time if that's ok with you.

**Comment by NathanNovak** [comment]
fixed with commit fec20d652a9860b93ee4427df272e65247cbc1b3
