### ISSUE TITLE
Shortcut functionality

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#23]
Shortcut behavior: Every measurement, sample, picture, etc. **makes a new point spot** in the background with the device’s current location. Going into the Notebook view makes it so you can take multiple measurements, etc. for a spot.

**Comment by NathanNovak** [comment]
Measurement, Sample, and Pictures have been completed.

**Comment by NathanNovak** [comment]
All shortcuts are now functioning.  last commit for Sketch Shortcut is b346805b159826168d40331f68bf70117610552b
