### ISSUE TITLE
Spots will not show after uploading to server

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#230]
If I upload a project to the server  the  spots disappear. See video.

Field Camp 2019     User fc24-19

https://user-images.githubusercontent.com/9283127/105616833-4395b500-5d9f-11eb-8073-6f24977fb0e7.mov

**Comment by NathanNovak** [comment]
Ok I see what happened.  A sneaky little dispatch to clear all the spots was placed.  

Fixed with commit 24f0b6aa7518217e8c44d816fa96f10faa44106d.
