### ISSUE TITLE
Offline dictation

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#231]
I thought that the dictation would work offline.  It only seems to work for a note when online

**Comment by NathanNovak** [comment]
Which device does dictation not work on offline?  If it is the mini then that may not have supported offline dictation. According to Apple "On iPhone 6s or later and iPad, you can use dictation without being connected to the Internet. Earlier models of iPhone and iPad require an Internet connection."

**Comment by NathanNovak** [comment]
Here is an issue from StraboSpot 1 that was dealing with that same issue in 2016:
https://github.com/StraboSpot/strabo-mobile/issues/265.

I did test Strabo Spot 2 on the IPad 11 pro and offline dictation worked just fine.

**Comment by NathanNovak** [comment]
Started working on @panamint55 Ipad. Closing issue.
