### ISSUE TITLE
Cannot add  spot near geolocate point

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#232]
https://user-images.githubusercontent.com/9283127/105617874-970c0100-5da7-11eb-9d19-5bf44d58b4e5.mov

**Comment by NathanNovak** [comment]
Maybe we should have a button that just adds a spot to the current location, like the shortcuts add the spot to the current location with a sample or measurement.

**Comment by NathanNovak** [comment]
@nicolasmroberts where should I add a button to add a spot to current location?
