### ISSUE TITLE
Some problems editing

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#235]
There are  some  issues  ediitng a  line or point.  Sometimes changing scale helps.  Not sure where this  comes from.

https://user-images.githubusercontent.com/9283127/105617981-5b256b80-5da8-11eb-8b25-578b1213b6dc.mov

https://user-images.githubusercontent.com/9283127/105617986-65476a00-5da8-11eb-805c-fa69cf618a49.mov

**Comment by sdamaraju** [comment]
#216 is the root cause for the second issue (2nd video) mentioned in this bug ticket

**Comment by sdamaraju** [comment]
@jessicagood can we close this issue, with the explanation provided on the call.
