### ISSUE TITLE
Compass recalibrate option

### ISSUE THREAD

**Issue by alexanderlusk** [StraboSpot/StraboSpot-Mobile#239]
When using the compass for measuring orientations, there should be an option to recalibrate the compass. I envision this being a small button in the main orientation window.

**Comment by NathanNovak** [comment]
@alexanderlusk From what I am reading the compass in newer models of iPad is calibrated in the device automatically.  Most of the compass apps that I have looked at, and some mapping apps that use a compass, will ask the user to rotate, shake, or move the device in a figure eight pattern to calibrate.  If the iOS device needs to radically re-adjust a calibration it will pop up a display.

!<img src="https://user-images.githubusercontent.com/35514146/106168252-4996e780-614b-11eb-9fcd-2611f855a79a.png" width="200" />

Some people have tested this by taking a magnet and placing it on the back of the device to throw off the sensors and then going through the steps below to re-align the sensors.  

A user can also follow these steps: 

Make sure the device is updated past 13.4.

Calibrate the compass – on iOS Enable the Compass Calibration service:
1. Click on the Settings icon.
2. Select Privacy.
3. Select Location Services.
4. Select System Services.
5. Turn Compass Calibration ON.
6. Open the built-in Maps App and follow the on-screen prompts to get an accurate location reading.
7. Press the lower left side arrow till it points up.

If your compass is not calibrated, a Calibration Circle screen will pop-up and you will be able to calibrate the compass by filling out that circle with figure 8 movements in the air.

At the end of this process you will note that the blue line of sight in the Maps application is pointing to the correct direction.
Your compass is calibrated.

I'll keep researching the subject to see if there will be a way, or a need, to force a recalibration.

These are some issues in Strabo Spot 1 with similar questions.

https://github.com/StraboSpot/strabo-mobile/issues/304
https://github.com/StraboSpot/strabo-mobile/issues/291
