### ISSUE TITLE
image gallery swiping

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#24]
When the modal view is open in the image gallery, you should be able to swipe to see the next picture

**Comment by NathanNovak** [comment]
@nicolasmroberts We fixed this issue with commit a05b4df78fd0d5a14a724abc11c42a1a14263657. Fixed bug and adjusted style with commit 951f1f0cafded571cc04794ed04c9e0c5013c08c.
