### ISSUE TITLE
Polygons are blocking point spots

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#25]
Right now, polygons are on top of point spots, so you can't click on the point spots. 

Polygons need to plot underneither points, or else you can never select the point spots

**Comment by sdamaraju** [comment]
@nicolasmroberts Hi Nick, We made few changes to make the "get spot at press" more accurate.
I tested the above scenario you mentioned. Can you please check with latest master build and let me know if we can close this issue.
Thanks,
Sai

**Comment by sdamaraju** [comment]
@jessicagood  can you please see this and let me know if I'm missing anything or if this can be closed immediately.

**Comment by nicolasmroberts** [comment]
@sdamaraju Selecting spots underneath polygons is now working properly, you can close the issue
