### ISSUE TITLE
Issue downloading Strabo2 onto Android phone

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/StraboSpot-Mobile#26]
I follow the link from the QR code and all I get is the attached page on my phone. When I click the link it seems to just refresh the webpage. Is this because I am using an android phone, or is there something else?

![Screenshot_20200210-132124_Chrome](https://user-images.githubusercontent.com/54119012/74182359-83a06e00-4c08-11ea-9d4b-d8f9e6850f4e.jpg)
.

**Comment by jessicagood** [comment]
Yes, the build is just for iOS.
