### ISSUE TITLE
Cannot remove an assigned tag from spot

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#265]
Steps
1. Add tag to spot.
2. Open tags from left panel
3. Select the tag from step 1.
4. See that the spot listed in step 1 is listed in spots list for this tag.
5. click the add/remove and try to unselect the tag.

Removing tag doesn't work.

**Comment by jessicagood** [comment]
The onPress was tied to the row not to the checkbox itself. Fixed with commit f6b57b3f23df9db8793e0f9b9ef2eb427066e63e
