### ISSUE TITLE
All spots pane swiping behavior fix

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#27]
Opening the all spots pane with a swipe is now working GREAT! But, it needs to close without closing the whole notebook. The swipe from right to left opens the all spots pane, and once it is open, a swipe from left to right should close it but leave the notebook open. An additional swipe from left to right (once the all spots pane is closed) should close the notebook.

**Comment by NathanNovak** [comment]
@nicolasmroberts The All Spots panel can be closed individually by swiping to the right with two fingers.  The gesture library being used has multiple finger swiping methods.  We just need to let the user know the operation
