### ISSUE TITLE
Blows up opening image gallery

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#274]
V. 0.25.2

I went to FC24-19 on a clean install and brought in from the server.  I activated the twin, north twin, and temple canyon datasets.  When I go to image gallery it either blows up after a couple seconds without showing anything but gray pictures, or it shows pictures and blows up when I try to scroll, or once it blew up with pictures showing but not trying to go thru the gallery.

I cannot make a video.  I start recording, but the video does not save when it kicks out of SS.

**Comment by panamint55** [comment]
Taken with my phone.

https://user-images.githubusercontent.com/9283127/107882015-acf37a00-6eac-11eb-8d32-b6d4d96e129a.mov

**Comment by NathanNovak** [comment]
@sdamaraju I changed the package to display the images to React-Native-Fast-Image.  There seems to be an improvement in the image loading, and on higher end iPads I couldn't get it to crash using fc24-19 and having North Twin and Twin Mountain active. @panamint55 said he had a crash on his although I am not sure which device he was using.  
Another option is to downgrade the images on download to be < 3 MB per image.

**Comment by NathanNovak** [comment]
fixed with PR eba9cf825caf4cb860e4a3140c826d7ce118777e
