### ISSUE TITLE
Text box CSS

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#28]
instead of the text box having a black outline and no fill, make the text box white fill with no outline and a slim padding around the edge.

**Comment by NathanNovak** [comment]
@nicolasmroberts Where are you talking about?

**Comment by jessicagood** [comment]
This is in the Notebook on the Notes page.

**Comment by sdamaraju** [comment]
Confirmed the fix over slack with Nick.

**Comment by sdamaraju** [comment]
closed with coomit 1a268a193807973a0e3f2e589770738074b30153
