### ISSUE TITLE
Screenshots for App Store and TestFlight

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#283]
I need to create an app in the Apple Developer portal for StraboSpot 2 and need to include screenshots.  We think it would be better to have screenshots with data on them and other functionalities geologist want to see when eventually downloading from the store.  Will you create a collection (3-10) of images and/or small videos to upload?

**Comment by nicolasmroberts** [comment]
Sure I can do that by the end of the day

**Comment by NathanNovak** [comment]
I uploaded the screenshots and description info to make the TestFlight version. I don't think we can change them.

**Comment by NathanNovak** [comment]
I am going to close this because we can edit the screenshots with each build for TestFlight.
