### ISSUE TITLE
Hide shortcut buttons when notebook is open

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#284]
Having the shortcut and notebook tab symbols open is confusing. Hide all shortcut buttons when the notebook is open.

**Comment by nicolasmroberts** [comment]
@NathanNovak @jessicagood that is a brilliant suggestion. **I still think they should be hidden when the notebook appears--it just becomes too many symbols.** But in addition, shortcuts really should have a modified symbol that lets the user know they are creating point spots when they add data via shortcuts. 

In the attached zip file, the new version of icons has a "Shortcut" modifier on some filenames, namely those that have shortcuts currently, e.g. SampleButtonShortcut.png and SampleButtonShortcut_pressed.png

Shortcut buttons should be changed to these file names. 

[icons_v_13.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6111019/icons_v_13.zip)

**Comment by NathanNovak** [comment]
finished with commit 76dfb33431a1cf87c63f58a51948d534467d51e4 - hiding the icons
Icon changes with commit 911bde6c3484bb1f9e4bc0cce31876799ad04bc1, 492c636c983337a2103f182b19fcc8404c66eeb8
There were additional commits but they had to do with GitHub not ignoring the case.
