### ISSUE TITLE
Profile Page Mockup

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#287]

**Comment by nicolasmroberts** [comment]
<img width="277" alt="Screen Shot 2021-03-12 at 10 06 44 AM" src="https://user-images.githubusercontent.com/35352527/110966218-a83eac00-831a-11eb-9131-993a8769ff46.png">

**Comment by nicolasmroberts** [comment]
of course using your standard form formatting and color that is strabospot2-wide

**Comment by NathanNovak** [comment]
Completed with commit b47f1a98c40293659636c3635b5e54bd373bce9a
