### ISSUE TITLE
Add point at current location button

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#288]
New icons, PointButtonCurrentLocation.png and PointButtonCurrentLocation_pressed.png. The button adds a point spot at the user’s current GPS location. From early feedback and my own testing, I think we need this button next to point, line, and polygon. It’s annoying to go into the geometry and “set to current location” every time.
[v15.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6131137/v15.zip)

**Comment by NathanNovak** [comment]
added with commit 13d235e889631f38ba55b14cb4fe290ed727e5c3
