### ISSUE TITLE
All Spots Panel: default selection

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#29]
When you first open the all spots panel, it should by default be scrolled down to the spot that is currently open in the notebook. That spot should be outlined in blue to show it is selected. 

This way, users can quickly navigate to the spots chronologically nearby the current spot.

**Comment by jessicagood** [comment]
@nicolasmroberts Are you still thinking the All Spots Panel will be useful? Without the swipe gestures it's not as quick to open. I gravitate towards using the Spots Lists in the main menu but not sure about everyone else. Just double checking before we put more work into this.

**Comment by nicolasmroberts** [comment]
@jessicagood I agree. **I think we can get rid of the all spots panel**. Between the "RECENT SPOTS" that displays in the notebook when no spot is selected and the spots list in the main menu, I think we've got navigating the spots list covered.

**Comment by NathanNovak** [comment]
Removed AllSpotsPanel with commit 9c88522586970529b722b7f0367cb354e9a7239d and a30945c08efa54a289e6f5291d84d1978d38d31e
