### ISSUE TITLE
New Ig/Met Icons

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#292]
@nicolasmroberts
The Ig/Met page is being broken up into separate pages so we'll need icons for the following pages. Thanks!

Ig Rocks
Met Rocks
Minerals
Reaction Textures
Economic (Alteration/Ore)

**Comment by nicolasmroberts** [comment]
[v16.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6159569/v16.zip)
@jessicagood 
New families of icons:

Igneous....png
Metamorphic....png
Minerals....png
Reactions....png
Economic....png

**Comment by jessicagood** [comment]
The new icons are a smaller file size and the lines are not as smooth. See below (new one is on right). Is this what you want?
![image](https://user-images.githubusercontent.com/1493985/111536775-eb888880-8727-11eb-98c4-d701618c2efa.png)

**Comment by jessicagood** [comment]
You can leave general Petrology icons in there for now too. I might need it in the Spots lists to display which Spots have pet data before I go through the more complex work of figuring out which type of pet data is in a particular Spot.

**Comment by nicolasmroberts** [comment]
Yup weird, my settings somehow changed in illustrator. 
[v16 2.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6159774/v16.2.zip)

these icons have the 264 ppi that iPad Pro displays use.

**Comment by nicolasmroberts** [comment]
[v17.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6159794/v17.zip)

how's this?

**Comment by nicolasmroberts** [comment]
[v17.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6159884/v17.zip)

These are 161x161

**Comment by nicolasmroberts** [comment]
[v18.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6159951/v18.zip)
turned smoothing on, these are smoother

**Comment by nicolasmroberts** [comment]
[v18.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/6160025/v18.zip)
Ternary included

**Comment by jessicagood** [comment]
Added with commit ccd8bf7bb72f87c285f91d44d662465f8c760a49
