### ISSUE TITLE
Toggle Symbol Labels on Map

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#293]
When viewing densely collected data on a map, the labels make the data unreadable. In the symbol modal, there needs to be an option to toggle whether labels are shown.
![IMG_2376](https://user-images.githubusercontent.com/35352527/84043683-3ccf4480-a96c-11ea-88ca-387fe0b05054.png)

_Originally posted by @nicolasmroberts in https://github.com/StraboSpot/StraboSpot-Mobile/discussions/276_

**Comment by sdamaraju** [comment]
@NathanNovak @panamint55 @nicolasmroberts @jessicagood 

I implemented the toggle labels on spots.
Can you please suggest where should the toggle setting go ?
For example I implemented it like below, it looks odd, so looking for better UX on this.

![Screen Shot 2021-04-09 at 2 21 19 AM](https://user-images.githubusercontent.com/28953643/114143996-74838180-98da-11eb-9ece-036243a2cfde.png)

**Comment by jessicagood** [comment]
Great! In the comment above it says the toggle should go in the Symbol modal. That's in the star icon on the map.

**Comment by nicolasmroberts** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35352527/114187428-98ac8600-990d-11eb-80ab-67e7d07e732e.png">

It should go just below "All Symbols"

**Comment by sdamaraju** [comment]
got it. Thanks @jessicagood @nicolasmroberts

**Comment by sdamaraju** [comment]
closed with commit 6b738d2
