### ISSUE TITLE
Implement Continuous Tagging like SS1

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#295]
https://user-images.githubusercontent.com/9283127/105617924-f4a04d80-5da7-11eb-9943-5bcb10b0d768.mov

_Originally posted by @panamint55 in https://github.com/StraboSpot/StraboSpot-Mobile/discussions/258_

**Comment by sdamaraju** [comment]
Closing with commit : 7ee3f073860f9315cb7552fb365b7c8ba1c8c293

**Comment by jessicagood** [comment]
@sdamaraju 
Need to make sure a key exists before you reference it or it can break the app. See
https://github.com/StraboSpot/StraboSpot-Mobile/blob/master/src/modules/spots/useSpots.js#L121

Also continuous tagging should be applied to all geometry types, not just Points.

**Comment by sdamaraju** [comment]
closed with commit c830e49da718d6aa7114fa00179446f09b4e77de
