### ISSUE TITLE
Non-standard ratio images don't load as basemaps

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#306]
**Describe the bug**
I tried to load a panorama as an image basemap. The map loaded as a black rectangle rather than the image.

**Comment by sdamaraju** [comment]
@nicolasmroberts  can you please elaborate by explaining and providing more details like screen captures and the image as well.

@jessicagood if its about panoramic image, is it an enhancement ? or should this be treated as bug. By panoramic image, I'm assuming it to have a greater width than regular images.

Please correct my understanding.

**Comment by jessicagood** [comment]
This should be treated as a bug. All images, no matter the sizes, ratio, heigh or width should be handled elegantly. Maybe @nicolasmroberts you could send us the actual image that is failing (or a few that have failed).

**Comment by nicolasmroberts** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/35352527/114187060-33f12b80-990d-11eb-9f1b-eba264676ce0.png">

@sdamaraju this is what loading a pano as a baseman looks like right now

**Comment by sdamaraju** [comment]
@nicolasmroberts I tried using a panoramic image, I clicked one using the ipad, it worked okay for me. It was just lengthier than other image basemaps (expected). Can you please let me know how did you capture your pano image.

**Comment by nicolasmroberts** [comment]
https://user-images.githubusercontent.com/35352527/114724260-fae7fb00-9d00-11eb-84ea-fa4357378a47.mov

@sdamaraju here is there full workflow that got me to the bug. The same thing happened when I stitched photos manually together, saved as a jpeg, and imported into Strabo.

**Comment by nicolasmroberts** [comment]
same thing happens if you crop a normal photo in the photos app to be an unusual ratio, then import using Strabo.

**Comment by nicolasmroberts** [comment]
Just to reiterate, this is a really common use case. The same bug occurs when I load (a normal aspect ratio) image imported from my nice camera (rather than the iPad camera). So it seems it is something about default resolution or something?

**Comment by sdamaraju** [comment]
@nicolasmroberts sorry for the delayed update, I reproduced this issue locally with the help of provided video, I'm currently analyzing the rootcause and will come with the best possible fix shortly. Thanks for your inputs.
