### ISSUE TITLE
SS2 blows up going from a picture in image gallery to notebook

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#307]
If you open the image gallery and select an image and then hit the notebook button in the lower right all is good.  It goes to the notebook.  If you scroll in the images and then hit the lower right the application blows up.  See movie

https://user-images.githubusercontent.com/9283127/113964772-ce5c4c80-97f1-11eb-9ba2-a6cc507c790e.mov

**Comment by sdamaraju** [comment]
work in progress.. Identified the issue. Fixing it.

**Comment by panamint55** [comment]
Another comment here.  See images.
1. When it blows up sometimes it kicks the user off and I have to login again.
2. If I log in again I have to reload the dataset, but not the photos.
3. Sometimes it blows up and you can go back in as the last user, it knows what project you are in, but it does not display any spots (image below).





![IMG_0247](https://user-images.githubusercontent.com/9283127/114314949-71e38080-9ac2-11eb-98ad-b24b5181ef3d.PNG)An
![IMG_0248](https://user-images.githubusercontent.com/9283127/114314950-727c1700-9ac2-11eb-8d0a-da9cc3e957cd.PNG



![IMG_0245](https://user-images.githubusercontent.com/9283127/114314941-67c18200-9ac2-11eb-9c06-aad999dd5674.PNG)
![IMG_0246](https://user-images.githubusercontent.com/9283127/114314943-6d1ecc80-9ac2-11eb-81d9-fe7852e7ca8b.PNG)

**Comment by sdamaraju** [comment]
closed with commit f7f36d87d28a4f5f6acd9d108a4d0b3f907deb7b
