### ISSUE TITLE
Remove "Add New Tag" from Tag Notebook page

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#309]
The "Add New Tag" button is redundant with the one in the Tag modal, and makes it sounds like the user clicks there to add a tag to the spot. In addition, **Change "Add New Tag" in the Tag modal to "Create New Tag"**. Clearer, I think.  

![Screen Shot 2021-04-09 at 10 49 03 AM](https://user-images.githubusercontent.com/35352527/114206832-58570300-9921-11eb-8215-a8a49c37273d.png)

**Comment by sdamaraju** [comment]
Closed with commit ab96cf4
