### ISSUE TITLE
Cannot get out of offline view

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#311]
When you go to manage offline maps you have the option of displaying the saved maps in offline map mode.  This is pictured below.  Once in this mode I do not know how to get out.  It says "offline view."  

I cannot figure out how to get back to the online view.

![IMG_1F90FCE82596-1](https://user-images.githubusercontent.com/9283127/114286708-d05b2100-9a26-11eb-9da5-1d1647320fb7.jpeg)

**Comment by NathanNovak** [comment]
To get out of offline view the user would need to select a different, or same, basemap from the Map Layers menu.  It isn't very obvious so I will do a toggle or a close button

**Comment by NathanNovak** [comment]
fixed with commit 5cdbb5640b8c8a9466690ef433e37dbfddf9e0ea
