### ISSUE TITLE
Download offline tiles is different.  Is this a planned change?

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#312]
in offline tile download, you get the message "gathering tiles" both when getting the tiles together and when downloading.  See images below.  It used to say "downloading tiles" during that stage.  Was this change intended?
![IMG_0242](https://user-images.githubusercontent.com/9283127/114314559-eb7a6f00-9ac0-11eb-9607-c37fea5f77e6.PNG)
![IMG_0243](https://user-images.githubusercontent.com/9283127/114314568-eddcc900-9ac0-11eb-86e9-e434eb15b3c2.PNG)

**Comment by NathanNovak** [comment]
Interesting.  I can look at this.  What I want to do is add a progress bar for each stage like in S1.  This issue may have some connection to #313

**Comment by NathanNovak** [comment]
fixed with commits 1cfa05048ef2ba6480d7af606e1c9a846d23536a and 5f28cfca810f0d72ba6398588ee3f72bb273aef0
