### ISSUE TITLE
Is the OK supposed to be active?

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#313]
When downloading images you get the "OK" blue all the time.  It can be pressed and then the dialog goes away.

It appears to still load in the background.  Is this the intended behavior?  

It is fine to do it this way, but just wondering if this change was intended.

![IMG_0244](https://user-images.githubusercontent.com/9283127/114314632-0c42c480-9ac1-11eb-90b9-0f98ed51a193.PNG)

**Comment by NathanNovak** [comment]
No the OK should be displayed when the download is complete.  There is an option to continue the download in the background.  I can get that fixed.

**Comment by NathanNovak** [comment]
fixed with commit bd67d177a49daefcb2aad2345f790d6745e45199
