### ISSUE TITLE
No way to get back to app if there are too many datasets when you upload to server

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#316]
I uploaded the FC24-19 to the server.  The dataset list was so long it went off the bottom of the page.  I could not get out of this without stopping/swiping the app.  When I came back I also had to log in again.  

![IMG_0249](https://user-images.githubusercontent.com/9283127/114808269-88f9cb00-9d6d-11eb-9b57-fa71383c5206.PNG)

**Comment by NathanNovak** [comment]
fixed with commit cc103baa0586a42f5c1310579d05c5af91d16979
