### ISSUE TITLE
images do not show in image basemaps

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#317]
I went to an imagebasemap, then looked at the enclosing spot.  After this I selected image basemaps again, selected one, but this time it would not show.  So, zooming to the spot messes up something with the image basemaps showing.  See attached video.

https://user-images.githubusercontent.com/9283127/115436978-3b4beb00-a1d1-11eb-90f6-46abe52d27a2.mov

**Comment by sdamaraju** [comment]
I'm evaluating this.

**Comment by NathanNovak** [comment]
@sdamaraju what is the update on this?

**Comment by sdamaraju** [comment]
fixed with commit : e842d822a0fdf3ff1504c5dd34015fe838491745
