### ISSUE TITLE
No warning when starting a new project

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#318]
I had and active project going, then selected "start a new project".  It started without any warning about the previous project.0.

https://user-images.githubusercontent.com/9283127/115442066-35590880-a1d7-11eb-9688-64e1c36f3f27.mov

**Comment by NathanNovak** [comment]
fixed with commits 3972b57924b4495f8ad217f27c7bf9cf6340a43d, 7a99f0332b4d13dbc1734013aad1cc81584ba95a, and a95456a38cb5075f8d4533b0baf80d6361ab4641
