### ISSUE TITLE
Selected Spot marker opacity with Multiple Measurements

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#32]
**Describe the bug**
When a spot is selected and a measurement is taken the opacity of the marker decreases with each measurement.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Select Spot
2. Take measurements
3. watch opacity decrease
4. repeat

**Expected behavior**
Opacity of the marker should remain the same despite how many measurements are taken 

**Screenshots**
![IMG_0147](https://user-images.githubusercontent.com/35514146/80035466-f3529500-84a4-11ea-84de-48c385890055.png)

**Smartphone (please complete the following information):**
 - Device: IPad Pro 11
 - OS: 13
 - StraboSpot 2 Version 0.3.1

**Additional context**

**Comment by jessicagood** [comment]
Fixed with commit e193a77
