### ISSUE TITLE
Image basemap remains on screen after deleted

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#324]
When a user selects to view an image basemap and then deletes it, the image basemap is still viewable on the screen until closed.

**Comment by NathanNovak** [comment]
Hi @sdamaraju,

Are you going to make a PR soon with this fix?

**Comment by sdamaraju** [comment]
fixed with commit : 17421eef0ad82465e17950d3486f51200f2c2ea8
