### ISSUE TITLE
Make measurement templates apart of project upload

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#342]
Students were discouraged when they had to redo their measurement templates when downloading or re-downloading a new project.  We need to make them apart of the project.

**Comment by jessicagood** [comment]
@jasonash The `templates` object is being sent to the server but is not in the response from the server when downloading the project. Can you add it when you get a chance? Thanks!

**Comment by jasonash** [comment]
Here is an example JSON string for testing:
`{
  "date": "2021-09-21T20:48:08.091Z",
  "projecttype": "app",
  "modified_timestamp": 1632257304032,
  "preferences": {
    "samples": true
  },
  "other_features": [
    "geomorphic",
    "hydrologic",
    "paleontological",
    "igneous",
    "metamorphic",
    "sedimentological",
    "other"
  ],
  "description": {
    "project_name": "Ssssss"
  },
  "id": 16322572880918,
  "self": "https://strabospot.org/db/project/16322572880918",
  "relationship_types": [
    "cross-cuts",
    "mutually cross-cuts",
    "is cut by",
    "is younger than",
    "is older than",
    "is lower metamorphic grade than",
    "is higher metamorphic grade than",
    "is included within",
    "includes",
    "merges with"
  ],
  "templates": {
    "minerals": {
      "isInUse": true,
      "templates": [
        {
          "id": "19821ead-c5a4-42e4-b44d-c80fa067aa6a",
          "name": "A Mineral Template",
          "values": {
            "mineral_abbrev": "Act",
            "full_mineral_name": "Actinolite",
            "igneous_or_metamorphic": "met_min",
            "habit_met": "subidioblast"
          }
        }
      ],
      "active": [
        {
          "id": "19821ead-c5a4-42e4-b44d-c80fa067aa6a",
          "name": "A Mineral Template",
          "values": {
            "mineral_abbrev": "Act",
            "full_mineral_name": "Actinolite",
            "igneous_or_metamorphic": "met_min",
            "habit_met": "subidioblast"
          }
        }
      ]
    }
  },
  "useContinuousTagging": false
}`

**Comment by jasonash** [comment]
The Project controller should be fixed now. It is now returning templates, relationship_types, and useContinuousTagging.

**Comment by jessicagood** [comment]
Great. Thanks!
