### ISSUE TITLE
Add Daily Setup Notes to Strabo2

### ISSUE THREAD

**Issue by srmulcahy** [StraboSpot/StraboSpot-Mobile#345]
Strabo1 had a feature called **Daily Setup Notes** that allowed users to take notes not tied to any spot. The feature was useful for documenting the goals of the field day prior to work and summarizing the observations at the end of the field day. The real value of the feature comes after exporting a pdf of the field notes because it provides a running narrative of the observations.

This feature is missing from Strabo 2. **Please add Daily Setup Notes**, or just call it _Daily Notes_ for keeping high level field notes for a given day that are not necessarily linked to specific spot.

**Comment by NathanNovak** [comment]
Hi @srmulcahy,

I added an 'enhancement' label to this and we should be able to get that added in a future release. I will keep this open until it is added.

Thanks!

**Comment by jessicagood** [comment]
Added with commit 4418441f60bb18586417b7f9b972a6f726ffb7df.
Will be in next release.
