### ISSUE TITLE
plotting measured linear features without type

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#350]
If make a linear measurement but don’t choose a Linear Feature Type the map draws a line arrow symbol that points to the north, even though it should point to the trend direction.

**Comment by jessicagood** [comment]
The arrow symbol points in the trend direction for me.  @panamint55 can you recreate this issue?

**Comment by jessicagood** [comment]
@panamint55 Unable to reproduce as well. Closing.
