### ISSUE TITLE
Quality of Measurement slider on compass doesn’t seem to do anything.

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#351]
Quality of Measurement slider on compass doesn’t seem to do anything.

**Comment by NathanNovak** [comment]
@JEAndrew what version are you running? Seems to work fine.

**Comment by JEAndrew** [comment]
yes, this was from May, so probably an older version.
________________________________

**Comment by NathanNovak** [comment]
@JEAndrew This was fixed with commit f16de69721cf5f7a4e5c8099c032e5a25ac978ea and is a duplicate issue from #341.The fix should be in the newest release in the App Store.
