### ISSUE TITLE
Help icon on home sidebar doesn't have help

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#355]
Help icon on home sidebar
-then About Strabo
♣	This just shows the version number of the app.
♣	Eliminate this? Show the version number on the tab level above?
♣	Eventually, this should pull up the help text document (that I’m creating)?
♣	Make into 2 separate items? A help button and app version shown

**Comment by NathanNovak** [comment]
@JEAndrew I am closing this because we have expanded the menu under the Help section to include Documentation.
