### ISSUE TITLE
recenter map when using shortcuts

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#356]
On my older little ipad the map did not recenter to the GPS position when the shortcut icons were used, but if it did it would make for a much better and intuitive tool

**Comment by NathanNovak** [comment]
Fixed with commit ce62a9d7fd2d4d598dd4c2a6ba2e523ac0bf52cd

**Comment by NathanNovak** [comment]
also fixed with commits 93779279b5075dbefd606565bab2256114b2f58b and ae812bf48c0fc346cdad32d71e361c1e7cef1726
