### ISSUE TITLE
When one clicks the location button, the longitude and latitude should be shown on the map. 

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#364]
When one clicks the location button, the longitude and latitude should be shown on the map.

**Comment by panamint55** [comment]
Where did this come from?  Maybe, maybe not.  I am not sure how much that will help anyone.

**Comment by NathanNovak** [comment]
I can't remember who said this but I put it in because someone thought it would be a good idea.  I can close it if you think it wouldn't
