### ISSUE TITLE
project upload failure

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#369]
I am using version 1.3.3 of StraboSpot2 on an i-pad mini.   The project properties and dataset properties upload fine, but then the app tries to upload spots for a long period of time with the 4 dots cycling. Eventually, (it varies from 5 minutes to overnight) the app returns a notice that the project failed to upload. The active project is only one dataset, but that dataset is relatively large with 1099 spots and 135 images. 

The MyData tab on the StraboSpot web interface shows 1099 spots. Recent edits appear to show up on the uploaded dataset accessed via the web. All of the images appear to be there. I can't tell that anything failed but I get this consistent error and the app takes a long time with this upload before it reports failure. 

The web strabspot account access for MyData-MyProjects only shows the date that the datasets were created/or first uploaded. This tool might be more useful if it also showed the date-time for the last uploaded or edits.

**Comment by NathanNovak** [comment]
@JEAndrew Have you updated the app to 1.6.0 from the App Store? We are now testing 1.7.0 in Test Flight. See if that helps any.

**Comment by NathanNovak** [comment]
@JEAndrew have you had anymore project upload issues?  I will close this issue unless you have and we need to explore it more.

**Comment by JEAndrew** [comment]
I haven't tried lately, I can redo my uploads and see if my issues were resolved. Thanks!
________________________________

**Comment by NathanNovak** [comment]
Sounds 👍

Nathan Novak
520-400-5793

**Comment by NathanNovak** [comment]
@JEAndrew have you had a chance to test the uploads?

**Comment by JEAndrew** [comment]
no, I've been swamped lately. I'll get to it this week and notify you when I do.
________________________________

**Comment by NathanNovak** [comment]
ok

**Comment by JEAndrew** [comment]
I am still having issues with uploading rock units polygons from shapefiles. Most GIS datasets for rock units are very simple, many are just the polygon, an item ID and the rock unit label. The strabospot datbase needs several additional fields filled to have polygons tagged with rock unit Labels. So uploading such a shapefile yields the polygon with no other data.

**Comment by NathanNovak** [comment]
Ok but the rest of the data is uploading alright? Can you make a
separate issue for that one when you get a chance?

**Comment by JEAndrew** [comment]
yes, so far OK, I'll upload a few more. I'll put a git hub issue specifically for the unit polygons.

________________________________
