### ISSUE TITLE
L + P measurements auto toggles off

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#37]
**Describe the bug**
In the measurement tool, each time you take a measurement, it resets to foliation -- ON, lineation --OFF. For example, if you have both linear and planar measurement toggled ON, the lineation measurement toggles itself OFF after one measurement. In order to take another L + P measurement, you need to manually toggle ON lineation each time. Happens in both shortcut and notebook measurement tool modes. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
YES

**Smartphone (please complete the following information):**
 - Device: Ipad Pro 10.5 inch
 - OS: iOS 13.4
 - StraboSpot Version 0.4.0

**Comment by sdamaraju** [comment]
This issue is not anymore replicable. @nicolasmroberts can you please confirm

**Comment by nicolasmroberts** [comment]
This issue has been fixed
