### ISSUE TITLE
Add crenulation to Linear Feature Type

### ISSUE THREAD

**Issue by srmulcahy** [StraboSpot/StraboSpot-Mobile#375]
It would be useful to have crenulation as an option for Linear Feature Type

**Comment by jessicagood** [comment]
@panamint55

**Comment by nicolasmroberts** [comment]
@jessicagood. This request makes sense, "crenulation" can be added to linear feature types. Do we need to do that with kobo forms? If so which branch of kobo forms is being used right now for linear features?

**Comment by jessicagood** [comment]
@nicolasmroberts @ellennelson10 Let me know when this is updated and I can pull it into the app and close this issue.

**Comment by nicolasmroberts** [comment]
@jessicagood we have added this to the kobo form. Should be good now. You can close it when you see that it has successfully deployed with crenulation in the linear feature type

**Comment by jessicagood** [comment]
Added with commit 600037cfec441cb055da6696140ace53b7f493d3
