### ISSUE TITLE
Failure to upload project to server

### ISSUE THREAD

**Issue by gavinpirrie** [StraboSpot/StraboSpot-Mobile#377]
**Describe the bug**
"Error Uploading Project Properties" when trying to upload to server.

Backs up to device normally.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes, starting new project and attempting to upload creates same error with no spots. Error occurs with no input into project description (notes, magnetic declination, etc.) as well.

1. Attempt to upload project to StraboSpot Server

**Expected behavior**
Successful upload to server.

**Screenshots**
![IMG_204EBDCFB265-1](https://user-images.githubusercontent.com/55846957/129392772-ca1bec20-1a1d-46da-860a-ddd0138e1208.jpeg)
![IMG_927E39AC0BF6-1](https://user-images.githubusercontent.com/55846957/129392971-0884ff45-494d-4816-acb3-53f038afcfa5.jpeg)
![IMG_797D9FA139BF-1](https://user-images.githubusercontent.com/55846957/129392977-76ca3934-eafa-4a3d-9abc-481f135b22f3.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11" 3rd Gen
 - OS: iPad OS 14.6
 - StraboSpot Version: 1.6.0

**Additional context**
N/A

**Comment by NathanNovak** [comment]
Hi @gavinpirrie. Try restarting the app and uploading the project again.  We are aware of this and are working to get a solution out soon.  Let me know if you are successful.

**Comment by gavinpirrie** [comment]
@NathanNovak 
I was unable to upload the new project without deleting and reinstalling StraboSpot2.

I was able to backup the project to the device, move the backup, delete and reinstall the StraboSpot2, and upload successfully to the server after restoring the project.

**Comment by NathanNovak** [comment]
@gavinpirrie ok thanks for the feedback.  The hard part is that this issue is so hard to debug.  I am going to see if I can add some kind of error reporting to give us some kind of lead on why it happens sometimes but not always.

**Comment by NathanNovak** [comment]
I am sending an updated app to TestFlight before we release to the App Store.  Are you familiar with TestFlight?  I can send you an invite to download and use the beta version of the app to test.  This way I can also get feedback and crash reports easier.

**Comment by NathanNovak** [comment]
You can also go to https://testflight.apple.com/join/IXZFyQx7 which is the public link for Test Flight for StraboSpot2

**Comment by gavinpirrie** [comment]
@NathanNovak yes I am familiar with TestFlight! I was in the StraboSpot2 TestFlight previously, but for some reason am not any more. I'll sign up again and get that going.

Thanks for the help!

**Comment by NathanNovak** [comment]
I am going to close this cause we have not had anymore complaints on this topic.
