### ISSUE TITLE
Long list of Custom maps

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot-Mobile#383]
**Describe the bug**
I have several custom maps. So many that the active layer menu is completely full and extends off the screen. I am unable to scroll through the list, making some of my basemaps inaccessible. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No
no

**Expected behavior**
Scrolling through entire list of basemaps

**Screenshots**
Image of list of basemaps
![image2](https://user-images.githubusercontent.com/90642583/133129430-4261b8cd-52d6-4ef9-99ab-0ea6657170ac.png)

Image of attempt to scroll - Note the Mapbox satellite and street views are inaccessible. Perhaps an issue with the sizing of the entire menu box.
![image1](https://user-images.githubusercontent.com/90642583/133129629-0962617e-cb7c-4a8f-8d54-8a207b6359d9.jpeg)

The issue is confounded in offline use by a lack of scrolling and larger boxes housing the basemap titles. See image below
![image0](https://user-images.githubusercontent.com/90642583/133129705-eca652d8-6696-4dae-bbae-d83d6a46a8a0.png)

**Smartphone (please complete the following information):**
 - Device:  iPad Pro
 - OS:  iOS14.7.1
 - StraboSpot Version 1.8.1

**Additional context**
Spoke over zoom on 9/13. Would like to use on 9/15.

**Comment by NathanNovak** [comment]
Fixed with commits cbe00f9de549a91a12c8c791a201f4e4da28a708 and c0caa241af6b71e8a4d6960aab881442ea7d7eac
