### ISSUE TITLE
Overlays initially require online viewing

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot-Mobile#384]
**Describe the bug**
I have saved maps for offline use with multiple levels of tiles. If I convert my offline map to an overlay, when I try to view the overlay it does not maintain the high-res tiles.

If I am offline the first time I view the overlays, there is no detail even after zooming in.

If I view the overlays while online I am able to zoom in and access the higher-res tiles. I can then switch to offline and view the overlay at all scales. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No
No

View all overlays online at all zoom levels prior to working offline. (This takes a long time)

**Expected behavior**
Ideally, maps saved for offline use should be capable of being activated as overlays while away from internet access. All layers of maps saved for offline use should be accessible if user chooses to view as an overlay while in the field.

**Screenshots**
Initial view of map in offline mode. (Map has been saved for offline use at multiple scales)
![image2(1)](https://user-images.githubusercontent.com/90642583/133136000-d9a811ee-cf03-4f6f-a732-b03c09b597e4.png)

Note this is an overlay based on an offline map titled Dhor_Initial.
![image1](https://user-images.githubusercontent.com/90642583/133136134-4d9fa0c0-28b0-4c96-8ea4-1628db68f083.png)

Offline view of overlay *after* viewing it in online mode.
![image0(1)](https://user-images.githubusercontent.com/90642583/133136226-11695e1c-ec93-4bd6-94a7-7185f661f6f1.png)

**Smartphone (please complete the following information):**
 - Device: iPad pro 11 inch
 - OS: 14.7.1
 - StraboSpot Version 1.8.1

**Additional context**

**Comment by NathanNovak** [comment]
@andrewkrh We have updated and fixed the issue in 1.9.0.  Currently if you want to use an overlay offline you must download the custom map as a basemap then switch it to an overlay.  Downloading the map as an overlay directly is not yet functional.
