### ISSUE TITLE
Geologic Unit Tags

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#385]
Separate geologic unit tags from the rest of the Tags - though only in what the user sees not in the data structure.

Main Menu - Put Geologic Units above Tags

Notebook - Put Geologic Units above Notes

**Comment by jessicagood** [comment]
Added with commit dc7be7303e7f97e506d93561b19f9cbf519f40e4

**Comment by jessicagood** [comment]
@nicolasmroberts I need an icon for Geologic Units. Now, I'm just using the Tags icon.

**Comment by panamint55** [comment]
We really have to get some new icon for this.

**Comment by panamint55** [comment]
If we separate geologic units, then when you select adding or editing a geologic unit then only units should come up.  The list should not include all the other types of tags.  Just geologic units.

Likewise, when you select the general tags, I do not think that the geologic units should show up in the list.  Just show the documentation, comment types of tags.

**Comment by jessicagood** [comment]
New icon added with commit 9780737a2ae4135463961adfab602d782a48732d

**Comment by jessicagood** [comment]
Fixed with commit fbca45da5693e3a95803061d1bab1ef18443139a

Still to handle: 
- Creating a new Tag with only allowing the tag type for the given page
- Editing a Tag with only allowing the tag type for the given page
- Tags Shortcut

**Comment by jessicagood** [comment]
Fixed "Creating a new Tag with only allowing the tag type for the given page" with commit 46085b66ea6c9306f7b754a3244664697804ce9c

**Comment by jessicagood** [comment]
@nicolasmroberts @panamint55 What do you want to do with the Tags Shortcut? Do we need a separate shortcut for Geologic Units? Right now you can just add Geologic Units through the Tags Shortcut.

**Comment by NathanNovak** [comment]
@nicolasmroberts did @panamint55 answer this in a meeting?

**Comment by jessicagood** [comment]
Added shortcut with commit 29f893ba6d80993c63cf8544497d063e12d90784

@nicolasmroberts I made a temporary icon for the button but we could use one that looks a little cleaner.

**Comment by jessicagood** [comment]
Except for getting better copies for all of the Geologic Units icons this issue could be closed.

**Comment by nicolasmroberts** [comment]
@jessicagood This is working really well. We will make a new icon.

I think we do want to have a shortcut that is dedicated to geologic unit tags, so we will make an icon for that as well.

**Comment by ellennelson10** [comment]
@jessicagood Here is a new icon package. It includes the standard icons for "GeologicUnit" and the shortcut icons. Also the fold geometry icons for hinge shapes (issue #207)  are added.
[StraboIcons_v20.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/7918990/StraboIcons_v20.zip)

**Comment by jessicagood** [comment]
@ellennelson10 Thanks for icons! A few things that need to be fixed with the package:
- Missing icons for Fold Attitude of Unknown
- `GeologicUnitShortcut.png` should be renamed to `GeologicUnitButtonShortcut.png`
- `GeologicUnitShortcut_pressed.png` should be renamed to `GeologicUnitButtonShortcut_pressed.png`
- `GeologicUnit_pressed.png` should be renamed to `GeologicUnitButton_pressed.png`
- `GeologicUnit_pressed_1.png` should be renamed to `GeologicUnit_pressed.png`
- `Sample_transparent_1.png` should be named `GeologicUnit_transparent.png`
- Missing icons for Sed Rocks (see issue #379)

**Comment by ellennelson10** [comment]
[StraboIcons_v21.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/7967036/StraboIcons_v21.zip)
@jessicagood Here is another icon package. It has the unknown fold attitude icon, a new sedimentary icon (see issue #379 ), and I fixed the naming issues for geologic units.

**Comment by jessicagood** [comment]
Geologic Unit icons updated with commit 180ad41117ab9dd9f574ac51a37ce34654e33d84
