### ISSUE TITLE
Measure tool

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#389]
It would be nice to have a measurement tool, at least a very simple one.  

Select the tool, click on a point on the map, click somewhere else, and get the distance.  Like the google earth measuring tool, but not as advanced.

If this is easy to implement, then there would be less of a rush on a scale bar.

**Comment by panamint55** [comment]
That sounds great.

**Comment by NathanNovak** [comment]
I am going to close this one now
