### ISSUE TITLE
Android: Viewing Image as a Basemap Crashes App

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#391]
**Describe the bug**
Viewing Image as a Basemap Crashes App

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to spot with an image
2. Click on toggle to view image as basemap
3. Press 'View as Basemap'
4. Boom...

**Expected behavior**
Not crash and show image as a basemap.

**Smartphone (please complete the following information):**
 - Device: Android S7 tablet
 - StraboSpot Version 1.12.1

**Comment by jessicagood** [comment]
Fixed with commit #23b5927dc1a43e10d6a13db7251ae6012366271e
