### ISSUE TITLE
If a spot is a trace the trace info should show

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#394]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by panamint55** [comment]
If a spot is a trace then the information should show. The rest of the notebook information does not make a lot of difference. But the spot characteristics for the trace are important.

**Comment by jessicagood** [comment]
So open a trace Spot with the trace feature detail already showing and **Not** the Spot Overview page or create a new view with both showing? Or add the trace detail to an Overview section? @nicolasmroberts Any ideas how this would look?

**Comment by panamint55** [comment]
![IMG_439E5FDC854F-1](https://user-images.githubusercontent.com/9283127/144946474-3af5aef1-7d4a-46d0-b949-39d7f2cdfa75.jpeg)
With a trace, this is what opens.  The blue text at the top is hard to see.  Perhaps make it black, or put the first couple parts of the classification above the geologic units line but below the trace slider.  A trace will seldom have a unit assigned to it.  The others stuff, notes, measurements, etc. may be populated.

**Comment by jessicagood** [comment]
Changed text color with commit 3071cd103fc6430a06c3097febedd4da142a859c
