### ISSUE TITLE
Sample naming seems to forget the prefix

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#395]
I have been having trouble with the sample numbering under naming convention.  I have changed the name a couple times but it keeps going back to Unnamed the next time I open the app.  It also does not seem to increment the number.

To repeat:
1. Change the name for samples
2. Make a sample
3. Quit the app
4. Look at the name for samples.

**Comment by NathanNovak** [comment]
Hi @panamint55, 

I did what you said to do in TestFlight 1.13.1 and am not coming across this issue. I posted a video in One Drive and shared it with you.

**Comment by jessicagood** [comment]
I'm unable to recreate this issue as well.
