### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot-Mobile#404]
**Describe the bug**
Whenever I manually quit the app or it crashes, I am logged out and anything not backed up is not saved.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Quit StraboSpot

**Expected behavior**
If I quit the app, I want to be able to open it again without having to log back in.

**Screenshots**
[RPReplay_Final1644955416.mov.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8074293/RPReplay_Final1644955416.mov.zip)

**Smartphone (please complete the following information):**
 - Device: iPad pro 3rd Generation
 - OS:  iOS15.3
 - StraboSpot Version: 1.18.0

**Comment by andrewkrh** [comment]
I am also experiencing this issue. 

    Device: iPad pro 3rd Generation
    OS: iOS15.3.1
    StraboSpot Version: 1.18.0

**Comment by NathanNovak** [comment]
@ellennelson10 and @andrewkrh I just put a new version on TestFlight (1.19.2) to test the profile page.  I will let you know when it is available (probably in the next day or so.

**Comment by NathanNovak** [comment]
Fixed with commit 68935e8b920e23c9f52f1ef10efdfe61864112af.
