### ISSUE TITLE
Offline Maps inaccessable

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot-Mobile#407]
**Describe the bug**
There are no offline maps available when disconnected from the internet, despite them being listed in the "Manage Offline Maps" menu.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?

Restarting the app has no effect.
Restarting the app and making a new project has no effect.

1. Add a custom map (tested with custom Mapbox style in new project - mapbox://styles/andrew-kr-h/ckzzxanfz000s15pe6s3aauo9)
2. Save map for offline use
3. View offline maps in "Manage Offline Maps"
4***. This step generates an odd behavior. The list of maps is originally empty. It slowly populates with the map most recently added, followed my other maps downloaded to the device that are not yet added to the project. Also note the number of tile is suspiciously the same on all maps listed (see screenshot 1).
5. Turn off wifi and bluetooth
6. Click Map Layers
7. No offline custom maps listed (see screenshot)
8. Listed number of tiles for Offline Default Basemaps is suspicious (see screenshot)
9. Tiles save in original project are visible offline
10. Mapbox OSM Streets not visible dispite having saved some tiles for offline use.
11. Turn Wifi back on
12. Custom Basemaps re-appear
13. "Manage Offline Basemaps" Still not accurate
14. 

**Expected behavior**
Offline basemaps to be visible

**Screenshots**
![IMG_0769b](https://user-images.githubusercontent.com/90642583/155756159-b0e7302e-82a2-4ecd-87df-3aeb7b83b1e3.jpg)
![IMG_0770b](https://user-images.githubusercontent.com/90642583/155756165-c8fbdf9a-0f12-4899-9d9e-c15ef5419a56.jpg)
![IMG_0771b](https://user-images.githubusercontent.com/90642583/155756168-29d5b63f-3d94-4bcf-ba61-1514a24b5a71.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 3rd gen
 - OS: 15.3.1
 - StraboSpot Version 1.18.0

**Additional context**
Closing and restarting the program is not possible without wifi, as user is logged off on close/crash.

When I discovered this bug I had does these things
    -deleted a custom map and then remade a map with the same ID
    -I am using a mix of Mapbox styles and GeoTiffs on the server
     -In the tile cache there was a folder named with my Mapbox ID, it had two EMPTY folders in it that were named with two style IDs I had uploaded.

**Comment by NathanNovak** [comment]
Fixed the offline maps not showing up in the list bug with commit a7125915c4bb3f3acfd80a315a0adacd6661ebec.  Couldn't replicate the suspicious tiles so let me know if this is still happening.

**Comment by andrewkrh** [comment]
Awesome, thanks Nathan! Should I look for this fix in 1.19.2?

**Comment by NathanNovak** [comment]
1.19.3 is being reviewed. This should fix both issues

Nathan Novak
520-400-5793
