### ISSUE TITLE
map extent option for geologic units shows other tag types

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#411]
Under home icon/settings & preferences/geologic units,  when the map extent is selected it lists the correct geologic unit tags within the map extent but it also lists all of the the 'other' tags in the project. The 'categorized' option does not list the 'other' tags

It should only show the geologic unit tags within the map view. (version 1.20.1 on ipad)

**Comment by NathanNovak** [comment]
fixed with commit fb58cdba87a85827699581d66a2644a0c12e344a
