### ISSUE TITLE
obtuse number in parentheses for tags page from the home icon 

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#414]
Under home icon/settings & preferences/tags, it correctly lists the tags (excluding geologic units) in the project. to the right of each tag name are two numbers in parentheses. these seem to be the # of instances of the tag in the project and the number in the active dataset, but it's not very intuitive. 

A ratio would be a better visualization. I would prefer an option to only show tags from the active datasets vs. tags from the entire project. A similar ratio would be useful on the Geologic Units tag page.

version 1.20.1

**Comment by NathanNovak** [comment]
Let me know if this needs further attention
