### ISSUE TITLE
zoom to extent of project not current location after initial project load.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#42]
Description :
Once the project is loaded, the app focusses on to the users location which may not be the actual project location. Zooming to project location would be an optimal solution.

Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Comment by jessicagood** [comment]
@sdamaraju can you look into this again? @panamint55 is getting a zoom to current location still instead of the extent of active datasets. The zoom to extent needs to happen not just from the sign-in screen but also when you switch a project.

**Comment by sdamaraju** [comment]
@jessicagood looking into this.

**Comment by sdamaraju** [comment]
@jessicagood @panamint55 
I looked into this, I pulled the latest binaries and tried to reproduce the issue, in vain.
It works pretty well to me. (Switching the projects, loading the projects as well)
There is one issue, which I fixed today, that's when we switch on and off the data sets, we are not zooming to appropriate extents, that part is taken care as part of the commit that I'm going to push in.

**Comment by sdamaraju** [comment]
@panamint55 We fixed this issue and now, even when the active data sets are turned on or switched off, the zoom to extent of spots gets triggered.
Please let us know if you are facing any issues on this, else we can drive this to closure.

**Comment by jessicagood** [comment]
@sdamaraju I'm finally working with a project not around my home location and noticed I am actually still getting this issue if I close the app and reopen it. It always zooms to my location on opening the app even if the map was centered on the data before closing the app. Was closing and restarting the app one of your test conditions?

**Comment by sdamaraju** [comment]
Oh, reopening the app, I think was never considered in my logic.
It covers reloading the project or switching the projects or switching the
active datasets.
I will look into this again.
Thanks for letting me know

**Comment by NathanNovak** [comment]
@sdamaraju where are we on this issue?  I would like to get some of these closed asap.

**Comment by sdamaraju** [comment]
@NathanNovak This one, was parked aside, as it had low priority compared to others.

**Comment by sdamaraju** [comment]
@panamint55 @jessicagood  this one is something I wanted to talk about in our call, but I missed.

So last time when we discussed on it, I remember professor Doug saying that, if we have to zoom to extent of spots only when reopening the app, it should be fine. What I don't remember is whether we are fixing this or closing the bug.

@panamint55 how was the experience of zoom to extent of spots in the last field camp ? Do you feel we need to handle this case as well where we zoom to extent of spots even while reopening the app or is there any other scenario where the app takes you to your location than to extent of spots.

**Comment by panamint55** [comment]
OK, here is how I see it now.
1) When you first open a project it sets the map to the current location.  That is actually fine.
2) You can then zoom to extent of spots, and that seems fine as well.  So it works.
3) This all seems fine, so I guess I would remove this as a bug, and let the app work the way it does now.
4) Nothing would be perfect, and folks can have different reactions.
5) As long as we can zoom to extent of spots, zoom to  single spot, I think things are good.

**Comment by sdamaraju** [comment]
Closing this bug, as per professor Doug's comments above.
