### ISSUE TITLE
Seds Strat Section Default Selected Spot

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#424]
When you have a strat column loaded in the map, when you tap on the strat column background (i.e., deselect spots), the strat column page should be selected. Right now, it just goes to recent spots. The problem with that is that you can "lose" your strat column in the list of spots and you can't add more layers. 

right now: 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/35352527/161822645-93711dcd-0c8f-4811-8b82-971bfd461a64.png">

should look like:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/35352527/161822766-df3e7088-813f-4662-b5b5-e7cfafc9f3ab.png">

**Comment by jessicagood** [comment]
Fixed with commit 1eba7264faff1af9c033fe9917c2285d5c143fc6
