### ISSUE TITLE
can't remove geologic unit tag from spot in notebook popups

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#425]
When using the geologic units editing panel within notebook it’s easy to add a label using assign/remove, which pulls up a list of geologic units tags to choose from and click.  

But if you re-enter the spot after choosing a geologic unit tag and click on GEOLOGIC UNITS to edit the units, the list of geologic unit tags does not show up. Instead a list all of the spots with with this tag opens up.

 It has a direction saying to add/remove but it doesn’t seem to do anything when you click on on of these spots except to select the spot itself can’t figure out how to remove a label or add another label. 

The same menus/popups should appear when there is already a geologic unit tag added to a spot, so tags can be turned off or added.

v 1.20.1

**Comment by NathanNovak** [comment]
Can you elaborate on the steps you took to cause this issue? I cannot replicate it.

**Comment by JEAndrew** [comment]
this is embarassing, i see what i doing, i was clicking on the subheading geologic units and not on the 'assign/remove'.


________________________________

**Comment by NathanNovak** [comment]
Lol oh ok so then I will close this issue.
