### ISSUE TITLE
Zoom to map area required for custom maps

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#43]
Area : Custom Maps

Describe the bug
In the list of current custom maps available, right now only delete option is available. Requirement open for zooming to the selected map area. The click on the zoom to map area will help to zoom to the exact custom map basement that is selected.

To Reproduce
Are you able to reproduce the problem in a new project after restarting the app?
Yes

Screenshots
<img width="887" alt="Screen Shot 2020-05-27 at 11 48 17 AM" src="https://user-images.githubusercontent.com/28953643/83048941-03afdf80-a010-11ea-97ad-cce517e8e4d9.png">

**Comment by NathanNovak** [comment]
fixed with commit c68822dc20b517a43c611031a62c04657c4d917f
