### ISSUE TITLE
changing pixel coordinates bricks app

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#433]
@NathanNovak If you manually edit the pixel coordinates of a spot on an image basemap, the app permanently goes blank, and you are forced to delete the app entirely from the iPad.

**Comment by NathanNovak** [comment]
Wow ok I will check that out asap!

**Comment by NathanNovak** [comment]
All fixed! commit e195f54b6d33705756a0ff37731fba09abfde4b8
