### ISSUE TITLE
Measurment Shortcut Mode

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot-Mobile#436]
When taking a measurement, if a user switches to "Shortcut Mode", takes a measurement then clicks "Go to Last Spot Created" a new spot is created at your current location instead of going to the last spot created.

One solution might be to just remove shortcut mode. It doesn't seem to be an essential feature and none of the other pages use it.

[RPReplay_Final1650990695.mov.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8565137/RPReplay_Final1650990695.mov.zip)

**Comment by NathanNovak** [comment]
Hi @ellennelson10.  The way you are describing the shortcut mode is the correct behavior that @nicolasmroberts wanted.  When the modal is in shortcut mode and a measurement is made then a new spot is created at your current location. All of the shortcut mode buttons create a new spot at your location while doing the assigned task.

**Comment by NathanNovak** [comment]
@ellennelson10 Can you and @nicolasmroberts talk about whether you want a user to have the ability to go to the Shortcut modal from the Notebook modal and vice versa?  It is easy to take that out.

**Comment by ellennelson10** [comment]
@NathanNovak We are just going to leave this for the time being.

**Comment by jessicagood** [comment]
Ok then closing this issue
