### ISSUE TITLE
Strat Column adding interval issue

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot-Mobile#438]
In version 1.23.0 there are issues adding intervals. At first it seemed like we were unable to add an interval (it just won't let you save). You can if you fill out every form in the quick entry modal Including the "notes". However it is then added to the wrong side of the axis.

Also there is no longer a way to add or edit grain size.

![IMG_0893](https://user-images.githubusercontent.com/91563766/166557389-7af17c39-6092-4e51-bc61-6c478acc9f6a.PNG)
![IMG_0892](https://user-images.githubusercontent.com/91563766/166557399-845bcc21-e0bd-408f-aed6-3e545536bbe9.PNG)
.

**Comment by jessicagood** [comment]
@ellennelson10 Can you should me the exact steps of for the interval you were trying to add? Specifically what the QEM filled out looks like. I'm not able to recreate the problem yet.

**Comment by ellennelson10** [comment]
[RPReplay_Final1651609582.mov.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8614097/RPReplay_Final1651609582.mov.zip)
@jessicagood Here is a video showing the issue.

**Comment by jessicagood** [comment]
Ok, that helped. It is a problem only on iOS, not Android, and related to **any** form, not specifically Add Interval. Troubleshooting it.

**Comment by NathanNovak** [comment]
There was an update to the Javascript engine that was enabled on iOS, called Hermes.  Once I disabled that and rebuilt then skip logic and intervals seemed to work just fine. Not sure why that would cause such specific issues but can research it more later. 

I am closing this issue for now but if it continues then we can reopen it.
