### ISSUE TITLE
Turning on a custom map, takes user to current location

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#44]
Describe the bug
Once the custom maps are displayed and user selects a custom map (toggle on), the current location on the map is pointed to user location and not the map area.

Are you able to reproduce the problem in a new project after restarting the app?
Yes (As per drop box comments)

Screenshots
<img width="925" alt="Screen Shot 2020-05-27 at 11 54 48 AM" src="https://user-images.githubusercontent.com/28953643/83049511-ea5b6300-a010-11ea-8709-e0941795b85a.png">

IOS device.

**Comment by NathanNovak** [comment]
fixed with commit 384610a9960ff7b4afb5fe11114537de531ed2cf and d21352bef58917e98a0d65558ed0f95361f34316
