### ISSUE TITLE
Save map for offline use, gets stuck while downloading.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#45]
Describe the bug
While downloading a map to save for offline use, the download gets stuck.

Are you able to reproduce the problem in a new project after restarting the app?
Yes (As per the drop box comments)

Screenshots
<img width="926" alt="Screen Shot 2020-05-27 at 11 58 47 AM" src="https://user-images.githubusercontent.com/28953643/83049980-75d4f400-a011-11ea-9738-e22a4b1e2d8c.png">

**Comment by NathanNovak** [comment]
Fixed issue with commit b5aca6b164aee0f6b3d418dcb40f0e942065c23a which is a merge of MapChanges branch.
