### ISSUE TITLE
Downloaded maps do not show up in offline maps.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#48]
Describe the bug
Mapbox downloads are successful but MapWarper downloads fail. Mapbox downloads, though complete the download, are not available in offline maps.

Are you able to reproduce the problem in a new project after restarting the app?
Yes (As per the comments in dropbox)

Screenshots
<img width="902" alt="Screen Shot 2020-05-27 at 12 21 56 PM" src="https://user-images.githubusercontent.com/28953643/83052276-b2eeb580-a014-11ea-9978-b88eb93ef266.png">

**Comment by NathanNovak** [comment]
Fixed.
