### ISSUE TITLE
Change "username" to "email address" on Login Screen

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot-Mobile#498]
I've had a few users recently contact me asking for their StraboSpot username. It turns out the issue is the login screen for StraboSpot2. Can we change the prompt text from "username" to "email address"? I think this will alleviate the confusion.

<img width="508" alt="Screen Shot 2023-03-21 at 1 08 04 PM" src="https://user-images.githubusercontent.com/7904402/226702874-2b3b0b64-cfde-4616-addc-33818e7dd9c0.png">

**Comment by NathanNovak** [comment]
fixed with commit 4d7ca09b7e54c16d68fd31c7954d463e1f54d0fd
