### ISSUE TITLE
Toggle different map symbols

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#57]
Need to be able to toggle on and off the various map symbols that appear. For example, perhaps the user only wants to view bedding symbols. 
![IMG_2379](https://user-images.githubusercontent.com/35352527/84043914-7dc75900-a96c-11ea-8590-9c6cd4254c6b.jpeg)

**Comment by jessicagood** [comment]
Added with commit d7f1d264c2d29275ac341969f936232f97f36e47.

@nicolasmroberts Check this out in the next version and see if it's working as you intended.

**Comment by nicolasmroberts** [comment]
@jessicagood This feature is almost working right. It doesn't seem to deal well with associated lines/planes, though. For example, I have a project with foliations, lineations, and fold hinges. However, when I toggle off foliations, the lineations (which are "associated lines" to the foliation) also disappear. They should instead be under a separate toggle "lineations"

**Comment by jessicagood** [comment]
@nicolasmroberts Would we use the lineation label for any linear feature measurements (primary or associated) that do not have a specific feature type assigned? If so what about planar and tabular features that do not have a specific feature type assigned? Should those be listed with a toggle too and what would their labels be?

**Comment by nicolasmroberts** [comment]
@jessicagood "linear feature" label for uncategorized lineation measurements. "planar feature" label for uncategorized planar measurements.

**Comment by nicolasmroberts** [comment]
@Jessicagood you can close this issue
