### ISSUE TITLE
StraboSpot My Maps not working

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#59]
**Describe the bug**
Unable to save StraboSpot My Maps custom map. Clicking the save button does nothing. I double checked that 1) the StraboSpot My Maps map was public on the strabospot.org website; 2) I directly copy and pasted the ID; 3) The same map uploaded to mapbox and map warper worked just fine.

**Comment by NathanNovak** [comment]
Fixed with commit 2e194ec47321c30d96acb6ea531a15e86976b41d and b475090fe9c0b1d61bcc070c1a398b1e0df4e949
