### ISSUE TITLE
sed structure icon

### ISSUE THREAD

**Issue by UASTeam** [StraboSpot/StraboSpot-Mobile#60]
**Describe the bug**
Link from sedimentary structure in sed structures tab to geomoji icon lost in last update, so the icon no longer displays when viewing the strat section.

**Comment by jessicagood** [comment]
@UASTeam This is for StraboSpot 1 https://github.com/StraboSpot/strabo-mobile. Closing for SS2 since Sed is not written for this version at all yet.
