### ISSUE TITLE
Compass Feature defaults to Planar on and Linear off always

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#62]
Describe the bug:
Once we have the linear feature on and planar feature off or (both features on) and take a measurement, then it goes back to planar feature on and linear feature off always.
It's expected to keep the same settings on, which were used to take the measurement.

Screen shot :
<img width="1353" alt="Screen Shot 2020-06-15 at 1 17 08 PM" src="https://user-images.githubusercontent.com/28953643/84635722-39f6c580-af11-11ea-9c4b-cfbc5e8cbb3b.png">
<img width="1250" alt="Screen Shot 2020-06-15 at 1 17 59 PM" src="https://user-images.githubusercontent.com/28953643/84635732-3d8a4c80-af11-11ea-92c0-96b6f41b7595.png">

**Comment by NathanNovak** [comment]
fixed with commit 9ea2f8d942cf0eaf346d3ef371ed09412f147725
