### ISSUE TITLE
No edit required once Trace feature turned on.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#69]
Describe the bug
Trace feature, once turned on, should open the options available to trace. No need for the extra edit button. Screen shot taken.
<img width="657" alt="Screen Shot 2020-06-15 at 1 01 03 PM" src="https://user-images.githubusercontent.com/28953643/84640362-336b4c80-af17-11ea-939d-4732a93cf2dd.png">

**Comment by jessicagood** [comment]
Fixed with commit d046783
