### ISSUE TITLE
General performance issues being observed across Strabo2

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#70]
Describe the bug
Strabo2 Sluggish and slowly performing compared to Strabo1.

The panel animations etc have to be revisited.

Similar issue like Zoom animation duration is controlled with animation duration set to 0.

**Comment by sdamaraju** [comment]
@StraboSpot/contributors @Professor Doug, Can you please elaborate specific instances for the same which will help us debug the right areas of the issue.

**Comment by sdamaraju** [comment]
Field camp comments from users : 

Facing issues with performance, responsiveness, performance, speed in general.
The users used SS1 and liked it. They see that SS2 will be much better, and appreciated the features, but the sluggishness was a barrier.  One student said his productivity was cut by 20% because of the speed difference.

**Comment by sdamaraju** [comment]
Pending on this item is to try and reduce the time between 2 clicks. 
Next steps : Its delay due to the Mapbox lib, try to upgrade to latest mapbox and check.

**Comment by sdamaraju** [comment]
tried with this release "@react-native-mapbox-gl/maps": "^8.1.0-rc.4", no improvement atleast on the clicks.

**Comment by sdamaraju** [comment]
Hi 
@jessicagood , Can we close this ticket, or are we planning to have any next steps of analysis on this ?
Please suggest.

**Comment by jessicagood** [comment]
Yes, I'll close it since it's too broad. If there are performance issues we can make new more specific issues.
