### ISSUE TITLE
Point, Line and Polygon icons

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot-Mobile#78]
@ nicolasmroberts We need icons for the the point, line and polygon icons that appear in the notebook header. I made NotebookHeaderLine.png and NotebookHeaderPolygon.png so we'd have something but not sure if we also need multiple size for those like the rest of the icons. 

In SS1 these icons also appeared in the Spots List so you'd know exactly what type of Spot it is before you open it. Not sure if you want them there or not. If you want them in other places besides the Header we probably should change the names from NotebookHeaderPoint, etc

Also, in SS1 I had a different point icon for a point mapped on a geo map vs on an image basemap vs strat section. So if you wanted to do that in SS2 we'd need those icons too.

Point Spot on an image basemap:
![image](https://user-images.githubusercontent.com/1493985/84829408-9246c980-afdc-11ea-99f1-814b49e0ba46.png)

Point Spot on a strat section:
![image](https://user-images.githubusercontent.com/1493985/84829442-a4c10300-afdc-11ea-9171-8556e3b425c2.png)

**Comment by jessicagood** [comment]
@nicolasmroberts

**Comment by nicolasmroberts** [comment]
Ok working on this

**Comment by jessicagood** [comment]
Cool. I think it's just the second part left ... if you want different icons for points, etc on an image basemap or strat section versus the defaults for a geographic map.

**Comment by jessicagood** [comment]
@nicolasmroberts Were these in you v7 icons zip?

**Comment by nicolasmroberts** [comment]
@no they were not. I’ll send you a version 8 with those and the other “cleanup” suggestions you made in another thread.
