### ISSUE TITLE
Performance issue: Saving map for offline Use

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#79]
Describe the bug
Saving map for offline use, works fairly okay for Mapbox maps, but Map Warper maps, there seems to be a performance issue.

**Comment by NathanNovak** [comment]
Tried to duplicate the issue to see if it was a server call delay or a performance delay.  I don't think its a app performance delay cause the timing of the calls to responses varied no matter which map I was trying to download.  

Closing this issue for now.
