### ISSUE TITLE
Offline maps : Open relevant location when opened.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#80]
Describe the bug

On clicking of the offline maps, the downloaded offline map should open the map area, that was focused while the “save map for offline use” action is performed

**Comment by sdamaraju** [comment]
Screen shot : Screen shots: Actual: Over zoomed to a user’s location, expected: Zoom to right level at the right area. 
<img width="818" alt="Screen Shot 2020-06-15 at 12 39 11 PM" src="https://user-images.githubusercontent.com/28953643/84835654-b09adc80-b051-11ea-86db-67b45e1839af.png">

**Comment by NathanNovak** [comment]
fixed with commit 93e552727f8f82ef213ff360f949c09e0acdf6be
