### ISSUE TITLE
Offline maps : Detailed layer missing on airplane mode.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot-Mobile#81]
Describe the bug
On Airplane mode, the offline map, doesn’t really give the detailed layer (not updating the pixels) upon zooming in. 
<img width="1257" alt="Screen Shot 2020-06-17 at 4 21 07 AM" src="https://user-images.githubusercontent.com/28953643/84835796-0079a380-b052-11ea-9b5b-d57062581c0f.png">

**Comment by NathanNovak** [comment]
same as #200. Fixed with commit 6a3947e564b0e46ddc2182a516576c1b0c114493 and df21908e4d4744746778bf6c7f18dafccc2258fa
