### ISSUE TITLE
Can't close photo description box

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#84]
**Describe the bug**
The "close" button does not work in the photo description window.

![IMG_21D21773E114-1](https://user-images.githubusercontent.com/35352527/84898379-c5d13480-b06c-11ea-9e86-8b2ad44fd771.jpeg)

**Comment by sdamaraju** [comment]
@nicolasmroberts This is already fixed in the latest release

**Comment by nicolasmroberts** [comment]
I must have missed the last release, sorry -- thought I had downloaded it. Confirmed that it is fixed
