### ISSUE TITLE
Mockup – Measurement templates

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#85]
Mockup of how to predefine a series of measurements

[MeasurementTemplates.pdf](https://github.com/StraboSpot/StraboSpot-Mobile/files/4792574/MeasurementTemplates.pdf)

**Comment by sdamaraju** [comment]
Hi @nicolasmroberts and @jessicagood 

I have a question on how will a user select any other template after selecting the first template.
Like, Suppose I define my new template as "Gneissic foliation", after sometime, I want to use another template say, "XYZ foliation", turning on and off "use templates", will still point me to the last used template which is gneissic foliation.

Should we introduce some kind of button or something to go back and show the list of planar templates available ?

<img width="263" alt="Screen Shot 2021-03-08 at 5 41 15 PM" src="https://user-images.githubusercontent.com/28953643/110396352-8224bd80-8035-11eb-94ea-0d1fa2490091.png">

Also, the wire frames show that we have to show the list of templates available at the bottom of the screen (Outside the compass modal) ? is that expected ? Can we get a better wire frame for it that shows, what part of the ipad does the list of templates outside the compass modal occupy ?

Though I'm still not yet there in my development, I'm just trying to have enough clarity before I reach that point.

**Comment by sdamaraju** [comment]
Also, is there a way to update or edit a template that is already created ?

**Comment by NathanNovak** [comment]
@sdamaraju and @nicolasmroberts is this issue completed?

**Comment by sdamaraju** [comment]
@NathanNovak Hey Nathan, this is issue is done, with a minor issue that is already present in notebook panel as well. 
So, I will be creating a new issue for that and close this issue.
I will clean up and close all the issues on my name today.

**Comment by sdamaraju** [comment]
This issue is fixed using commit 5ee00eef1de74b0efdfc0f70597cbe897ddf8808, 

Opened issue #303 for tabular/planar orientation switch issue.
