### ISSUE TITLE
Mockup – Tags

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#86]
Shortcut and Notebook view for tags, along with the preferences pain for tabs
<img width="779" alt="Screen Shot 2020-06-12 at 1 03 30 PM" src="https://user-images.githubusercontent.com/35352527/84900271-7809fb80-b06f-11ea-819c-0b1143de17fd.png">
<img width="784" alt="Screen Shot 2020-06-12 at 1 03 47 PM" src="https://user-images.githubusercontent.com/35352527/84900336-8f48e900-b06f-11ea-9fa4-ae7a84360699.png">
<img width="908" alt="Screen Shot 2020-06-12 at 1 58 23 PM" src="https://user-images.githubusercontent.com/35352527/84900350-940d9d00-b06f-11ea-9992-b1a931159a8b.png">

**Comment by jessicagood** [comment]
@sdamaraju Can you add the `Filter Tags by Type` to the list where you select Tags - used in the Shortcut modal and when you Assign/Remove from the Notebook panel.

**Comment by sdamaraju** [comment]
pending on this : remove the filter from notebook and make the filter a dropdown instead of a text input

**Comment by sdamaraju** [comment]
Fixed the pending UI change using commit 134984c27fb74f8a907fb470fa62a3c970db536b

**Comment by jessicagood** [comment]
@sdamaraju Just noticed that filter dropdown displays the field name instead of the label. For example we shouldn't be showing `geologic_unit` to the user, it should be `Geologic Unit`. You don't need to to add the labels manually but use `tagsDictionary` which we're already using other places.

**Comment by sdamaraju** [comment]
Fixed with commit 7ee3f073860f9315cb7552fb365b7c8ba1c8c293
