### ISSUE TITLE
Point spots need Geography info page

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#88]
Clicking on the blue coordinates underneath the spot name should bring up a notebook page that has all the info of the "geography" section in Strabo 1 spot page.
![image (1)](https://user-images.githubusercontent.com/35352527/84900853-49405500-b070-11ea-88f6-c99b4125135b.png)
![image](https://user-images.githubusercontent.com/35352527/84900867-4e9d9f80-b070-11ea-9749-59701fdcfb7c.png)

**Comment by jessicagood** [comment]
Added with commit f83d7786b227644dd11b81530a044921bd9bee1f
