### ISSUE TITLE
Setting Copied Spot Disappears in Editing Mode.

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot-Mobile#90]
**Describe the bug**
When setting a spot to the current view and editing the copied spot disappears after moving to location.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Copy Spot
2. Click on 'Set in Current View'
3. Move spot to new location.
4. Save Edits

**Expected behavior**
The spot should be viewable on the may when moving to different locations

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPad 11
 - OS:13
 - StraboSpot2 Version 4.0

**Additional context**

**Comment by jessicagood** [comment]
Fixed with commit 3d04731484d8337cd08a09bdceb98bdff6a02b0d
