### ISSUE TITLE
Higher resolution app icon

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#91]
The app icon appears blurry or low res. Here is a high res copy

![straboicon-01](https://user-images.githubusercontent.com/35352527/85036345-a6f4a000-b149-11ea-9ee7-48c8a3166ae0.png)

**Comment by NathanNovak** [comment]
@nicolasmroberts - On the IPad home screen? Should I replace all the S2 icons with this one?

**Comment by jessicagood** [comment]
@nicolasmroberts @NathanNovak Stale issue for you both to review.

**Comment by nicolasmroberts** [comment]
Yup, it looks good.
